### PR TITLE
integration tests

### PR DESCRIPTION
**Pull request by hendrikebbers**
docker based integration tests

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/281)

### CODE REVIEW

**Comment by timo0** [comment]
*[integration-tests/integration-tests.gradle, line 14 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa39Ou5O43N1G9DVTm:-KZa39Ov1HPePOTMcHHQ:bus3vz7) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/integration-tests/integration-tests.gradle#L14)):*
> ```Gradle
> 
> dependencies {
>     compile project(':dolphin-platform-client')
> ```

testCompile?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
*[integration-tests/docker-base/payara-integration/todo-app.war, line 0 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa3aLpS-2ofQGg9zvL:-KZa3aLpS-2ofQGg9zvM:bvc3pkw) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/integration-tests/docker-base/payara-integration/todo-app.war#L0)):*
Create Issue for automate the Build of the war

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
*[platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoViewBinder.java, line 37 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa5ZJWpocQuvC6IMFw:-KZa5ZJWpocQuvC6IMFx:byp18fd) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoViewBinder.java#L37)):*
> ```Java
> import static com.canoo.dolphin.todo.TodoAppConstants.CONTROLLER_NAME;
> 
> /**
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
*[platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/TodoAppConstants.java, line 3 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa5mZ6XrZEByi_KqOG:-KZa5mZ6XrZEByi_KqOH:byp18fd) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/TodoAppConstants.java#L3)):*
> ```Java
> package com.canoo.dolphin.todo;
> 
> /**
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
Reviewed 16 of 18 files at r1.
Review status: 15 of 18 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by hendrikebbers** [comment]
Review status: 12 of 63 files reviewed at latest revision, 4 unresolved discussions.

---

*[integration-tests/integration-tests.gradle, line 14 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa39Ou5O43N1G9DVTm:-KZa6G7Zbh66ILMvDiiC:b-896fix) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/integration-tests/integration-tests.gradle#L14)):*
<details><summary><i>Previously, timo0 (Timo B) wrote…</i></summary><blockquote>

testCompile?
</blockquote></details>

Done.

---

*[platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoViewBinder.java, line 37 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa5ZJWpocQuvC6IMFw:-KZa6IIpK8Hy1oVRe7AR:b-896fix) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoViewBinder.java#L37)):*
<details><summary><i>Previously, timo0 (Timo B) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/TodoAppConstants.java, line 3 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa5mZ6XrZEByi_KqOG:-KZa6J0ZyECpDAZ8leZv:b-896fix) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/platform-examples/todo-example/todo-common/src/main/java/com/canoo/dolphin/todo/TodoAppConstants.java#L3)):*
<details><summary><i>Previously, timo0 (Timo B) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
Reviewed 1 of 48 files at r3.
Review status: 13 of 63 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by hendrikebbers** [comment]
Review status: 13 of 63 files reviewed at latest revision, 3 unresolved discussions.

---

*[integration-tests/docker-base/payara-integration/todo-app.war, line  at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/281#-KZa3aLpS-2ofQGg9zvL:-KZa6bSJ0Xin-frAlXHA:ba19juk) ([raw file](https://github.com/canoo/dolphin-platform/blob/92aa08592f4c8303c29db9664c35a4d65639b7c1/integration-tests/docker-base/payara-integration/todo-app.war#L)):*
<details><summary><i>Previously, timo0 (Timo B) wrote…</i></summary><blockquote>

Create Issue for automate the Build of the war
</blockquote></details>

issue created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
Reviewed 1 of 2 files at r2.
Review status: 14 of 63 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Comment by timo0** [comment]
Reviewed 1 of 18 files at r1, 1 of 2 files at r2, 47 of 48 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/281)*

**Pull request merged**
