### PR TITLE
Server Refactoring

### PR DESCRIPTION
**Pull request by hendrikebbers**
This pull requests contains a refactoring of some internal (not public) server APIs:
* Classpath scan is defined in an extra class
* Better structure of the DolphinContext class
* Additional test
* Task Executor is removed
* ControllerRepository isn't a singleton anymore
* Marked some methods as deprecated

This changes are needed / very useful to continue work on several work:
* EventBus refactoring
* DolphinContextListener concept on the server
* Better Lifecycle handling

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/99)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvP55L9VHEwNTbbygb:-KAvP55L9VHEwNTbbygc:-161529795) ([raw file](https://github.com/canoo/dolphin-platform/blob/52522d2f3d5ffb3e5e015441bed5a0ceb02d07dc/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L44)):*
why was this type/method removed? is there no need to deprecate instead?

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 58 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPTbzoYhcjWnTJQ1P:-KAvPTc-J0_mpiNtcUM6:1603392995) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L58)):*
wouldn't it make sense to supply this instance as a constructor arg?

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPnh7YnYpHi9ysq4q:-KAvPnh8oqdK9xNOaEZB:452556684) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L1)):*
file header

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPtVC46SNDtVlxZaS:-KAvPtVDicFSBotj9mSR:262225877) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L49)):*
why is this method synchronized?

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 54 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvQ6QYYL2za82n8aE4:-KAvQ6QYYL2za82n8aE5:-1812204673) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L54)):*
I definitely don't like all these magic singletons lying around in the codebase. It couples types too much and hinders testing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/99)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvP55L9VHEwNTbbygb:-KAzJ3yDgRodv_1CVsay:-836292766) ([raw file](https://github.com/canoo/dolphin-platform/blob/52522d2f3d5ffb3e5e015441bed5a0ceb02d07dc/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L44)):*
What method do you mean? Can't see any change here

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPtVC46SNDtVlxZaS:-KAzIeId6Ejf6AkvCi9z:234324380) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L49)):*
I have no idea if the reflections API can be used async

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 54 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvQ6QYYL2za82n8aE4:-KAzIhAJRAqCOOrgkaao:1553522425) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L54)):*
I already removed some singletons (ControllerRepository). For this class there are tests. If this won't be a singleton we need to pass it around with each constructor.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/99)*

**Comment by aalmiray** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvP55L9VHEwNTbbygb:-KB3W04PTzJP5J59tMyD:1649730995) ([raw file](https://github.com/canoo/dolphin-platform/blob/52522d2f3d5ffb3e5e015441bed5a0ceb02d07dc/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L44)):*
I meant the method that created a `TaskProcessor`.. Looks like the whole type has been removed now

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPtVC46SNDtVlxZaS:-KB3WD1ZQg6zPtbT2-eD:-1349716935) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L49)):*
then I suggest to find out instead of using `synchronized` like this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/99)*

**Comment by hendrikebbers** [comment]
Review status: 31 of 47 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvP55L9VHEwNTbbygb:-KBJyia6MninpImLItiw:-1974082326) ([raw file](https://github.com/canoo/dolphin-platform/blob/52522d2f3d5ffb3e5e015441bed5a0ceb02d07dc/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L44)):*
Yes, this was deprecated since several versions and as far as I know it's not used in any project.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 58 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPTbzoYhcjWnTJQ1P:-KBJyvh4z_FdbaWgcy72:-1031739464) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L58)):*
Currently the DolphinContextHandler is a singleton. But this will be refactored as a next step.

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPnh7YnYpHi9ysq4q:-KBJzjHvOuyYtsemGHQ5:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L1)):*
done

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/99#-KAvPtVC46SNDtVlxZaS:-KBK1opdc9XsCIN0ZleD:1007537157) ([raw file](https://github.com/canoo/dolphin-platform/blob/87adc961caa625e0eacb62feb224fdda374e2974/java-server/src/main/java/com/canoo/dolphin/server/impl/ClasspathScanner.java#L49)):*
https://github.com/canoo/dolphin-platform/issues/111

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/99)*

**Comment by hendrikebbers** [comment]
@aalmiray don't want to merge this without your final review :)

**Comment by aalmiray** [comment]
Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/99)*

**Pull request merged**
