### PR TITLE
Executor Interface is used instead of custom UIThreadHandler

### PR DESCRIPTION
**Pull request by hendrikebbers**
The UIThreadHandler interface is removed and replaced by the default Java Executor interface

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/356)

### CODE REVIEW

**Comment by netopyr** [comment]
Reviewed 18 of 20 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/ClientDolphin.java, line 52 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwJCMW4G-hEVx9CumT:-KcwJCMW4G-hEVx9CumU:b-rm3aun) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/ClientDolphin.java#L52)):*
> ```Java
>      * Convenience method for a creating a ClientPresentationModel with initial null values for the attributes
>      */
>     @Deprecated
> ```

Marking all of these methods does not really belong in this pull request, but I guess it is ok anyway.

---

*[remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java, line 84 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwAbdtEVnup2HDBvdm:-KcwAbdtEVnup2HDBvdn:b-9zifc4) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java#L84)):*
> ```Java
>             public void handle(final Throwable e) {
>                 LOG.log(Level.SEVERE, "onException reached, rethrowing in UI Thread, consider setting AbstractClientConnector.onException", e);
>                 if (executor != null) {
> ```

Does it make sense to run DP without an Executor?

---

*[remoting/dolphin-remoting-combined/src/main/java/core/comm/DefaultInMemoryConfig.java, line 43 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwK28dpmXIkUWYjw5P:-KcwK28e1DLO3Vvmh4Pa:bgu5v4s) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-combined/src/main/java/core/comm/DefaultInMemoryConfig.java#L43)):*
> ```Java
> 
>     public DefaultInMemoryConfig() {
>         this(new Executor() {
> ```

You are using this implementation quite often. Maybe you want to create it once in a central place and reuse it.

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/FunctionalPresentationModelTests.groovy, line 262 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwKWma5e2T6DAoV39G:-KcwKWma5e2T6DAoV39H:b-vtip2c) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/FunctionalPresentationModelTests.groovy#L262)):*
> ```Groovy
>     }
> 
>     @Ignore
> ```

Is this the Groovy Issue you mentioned yesterday? You should leave a comment and create an issue to remind you to enable the test again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/356)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-combined/src/main/java/core/comm/DefaultInMemoryConfig.java, line 43 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwK28dpmXIkUWYjw5P:-KcwjUD-LRloSHsWMRTK:b-896fjx) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-combined/src/main/java/core/comm/DefaultInMemoryConfig.java#L43)):*
<details><summary><i>Previously, netopyr (Michael Heinrichs) wrote…</i></summary><blockquote>

You are using this implementation quite often. Maybe you want to create it once in a central place and reuse it.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/356)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java, line 84 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-KcwAbdtEVnup2HDBvdm:-KcwjtTVDAwpNHEE08Hv:buzycfx) ([raw file](https://github.com/canoo/dolphin-platform/blob/0a66cbf00ce0a93d9cb52468fa9c4ca36443efff/remoting/dolphin-remoting-client/src/main/java/org/opendolphin/core/client/comm/AbstractClientConnector.java#L84)):*
<details><summary><i>Previously, netopyr (Michael Heinrichs) wrote…</i></summary><blockquote>

Does it make sense to run DP without an Executor?
</blockquote></details>

There are unit tests for this behavior. I think it does not make sense but will remove it in a later step.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/356)*

**Comment by netopyr** [comment]
:lgtm:

---

Review status: 18 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/356#-:-KcwlgEaJq91ktoCFk4J:bnfp4nl)*

**Pull request merged**
