### PR TITLE
(WIP) Moved SPI

### PR DESCRIPTION
**Pull request by Jarota**
Attempt no.2 at my first contribution: used eclipse's refactor option to move the spi folder

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/666)

### CODE REVIEW

**Comment by Jarota** [comment]
I've made progress but the build fails on "sonarqube" now, lost again as to how to proceed 😨

**Comment by hendrikebbers** [comment]
No problem. You do not need to to the full build. Sonarcube is not needed for your changes. It is only needed to check the quality of the API later.

Just do:

`./gradlew clean build
`

**Comment by Jarota** [comment]
`./gradlew clean build` works for about 54% of the build but then fails as below?



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration-tests:composeUp'.
> A problem occurred starting process 'command 'docker-compose''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by hendrikebbers** [comment]
@Jarota this looks already quite good. The point that is missing are the integration tests. For them Docker (docker-compose) is used to set up several servers with Dolphin Platform applications that will automatically tested in parallel. So you need to install docker on your system :)

**Comment by Jarota** [comment]
I've now installed docker on my system but the composeUp test still fails :cry:  Is there a specific test/edge docker repository I need to be working from?

**Comment by hendrikebbers** [comment]
Hi @Jarota is the test still failing with the same message or is it a new problem?

**Comment by Jarota** [comment]
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':integration-tests:composeUp'.] from daemon DaemonInfo{pid=2653, address=[aa09748f-d320-4ed5-a5d1-767c79f78ef0 port:42923, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=false, lastBusy=1508323111222, context=DefaultDaemonContext[uid=9a3f4273-4806-4d9f-8fad-5a849b661ec1,javaHome=/usr/lib/jvm/jdk1.8.0_144,daemonRegistryDir=/home/jammygit/.gradle/daemon,pid=2653,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done)


It is the same error message, but this is the end output when run with --info, does the HeapDumOnOutOfMemoryError mean I just need to assign more memory? (running on a vm)

**Comment by hendrikebbers** [comment]
Maybe that is the problem. I'm not an Gradle expert. Maybe @aalmiray can say something.

**Comment by Jarota** [comment]
@hendrikebbers I've actually got 9Gb free to work with which should be enough? There is this exception:

WARN 23673 --- [    Test worker] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

And a null pointer exception too:

WARN 23673 --- [    Test worker] org.reflections.Reflections              : could not create Dir using directory from url file:/home/jammygit/code/dolphin-platform/platform-integration-tests/integration-server/build/resources/test. skipping.

    java.lang.NullPointerException: null
        at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:239) ~[reflections-0.9.10.jar:na]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:98) [reflections-0.9.10.jar:na]
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) [reflections-0.9.10.jar:na]
        at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar:na]
        at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar:na]
        at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar:na]
        at com.canoo.dp.impl.server.scanner.DefaultClasspathScanner.<init>(DefaultClasspathScanner.java:76) [dolphin-platform-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]

**Comment by hendrikebbers** [comment]
@Jarota this is interesting. Can you please create an issue at Dolphin Platform and at reflection lib that is used internally: https://github.com/ronmamo/reflections

**Comment by hendrikebbers** [comment]
@Jarota can you create the issues? otherwise I will do it next week.

**Comment by hendrikebbers** [comment]
Once the issues are there we can merge this PR

**Comment by hendrikebbers** [comment]
about the PR:
there are some Java SPI related files that use the interface to load plugins at runtime. See https://github.com/canoo/dolphin-platform/blob/master/platform/dolphin-platform-distributed-eventbus/src/main/resources/META-INF/services/com.canoo.platform.remoting.server.spi.EventBusProvider as an example. This must be changed, too

**Comment by Jarota** [comment]
One issue here for the null pointer exception and one over at reflection lib for the warnings?

**Comment by hendrikebbers** [comment]
Yes. And both should be linked with this PR

**Comment by hendrikebbers** [comment]
@Jarota thanks for creating the issues. As said in one of my last comment there are still files in DP that are affected by this PR and need to be changed. Example: https://github.com/canoo/dolphin-platform/blob/master/platform/dolphin-platform-distributed-eventbus/src/main/resources/META-INF/services/com.canoo.platform.remoting.server.spi.EventBusProvider 

Please add another commit with the needed changes so that I can merge the PR. And many thanks for not giving up here. PR 666 looks like it's the evil PR :smiling_imp: :sweat_smile:

**Comment by hendrikebbers** [comment]
@Jarota do you plan to continue here?

**Comment by Jarota** [comment]
Apologies @Hendrik, I'm a bit snowed under with college work right now but
I'll be happy to continue next week!

**Comment by hendrikebbers** [comment]
Cool! No stress!

Von meinem iPhone gesendet

> Am 24.10.2017 um 23:02 schrieb Jarota <notifications@github.com>:
> 
> Apologies @Hendrik, I'm a bit snowed under with college work right now but
> I'll be happy to continue next week!
>

**Comment by Jarota** [comment]
@hendrikebbers Is that last commit what you're talking about?

**Pull request closed without merging**
