### PR TITLE
Type safe Event Bus

### PR DESCRIPTION
**Pull request by hendrikebbers**
The event bus is type safe (by generics)
ToDo Example uses event Bus and syncs the state of ToDos

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/9)

### CODE REVIEW

**Comment by fdreier** [comment]
Definitely an improvement over the version that only returns Object in my opinion, although slightly more difficult to call publish and subscribe (a Topic must be created).

**Comment by hendrikebbers** [comment]
@fdreier mmh, normally you would create a topic as a static String an reuse it:

private final static String ADD_TOPIC = "add_item";

With the new version you create a Topic instance mainly the same way:

private final static Topic<DataType> ADD_TOPIC = Topic.create("add_item");

Don't think that this is more complex :)

**Comment by Dierk** [comment]
Hm - this change is about making it more type safe?

**Comment by fdreier** [comment]
@hendrikebbers , or you could write 
private final static Topic ADD_TOPIC =  new Topic("add_item");

so there are two possibilities -> therefore SLIGHTLY more complex ;)

**Comment by hendrikebbers** [comment]
@Dierk @fdreier  Oh, Markdown removed some chars in the code block. Now it's formatted as code and the generics are visible:

    private final static Topic<DataType> ADD_TOPIC = Topic.create("add_item");

By using the Topic you can only send data of type __DataType__ to the topic. In addition you can only register listeners for the given type (__DataType__). This gives you type safety at development time. If you only use Strings or a Topic without generics you need to cast all data to the specific type in the listeners:

    eventBus.subscripe(NOT_GENERIC_TOPIC, data -> ((DataType) data).someMethod());

 In addition you can't send a different type when using generics since the code won't compile:

    eventBus.publish(GENERIC_TOPIC, dataOfWrongType); <-- This won't compile

**Comment by hendrikebbers** [comment]
@fdreier The two calls

    Topic<Data> t = new Topic<>("name");

and
    
    Topic<Data> t = Topic.create("name");

does exactly the same. We can remove the static create-methods if this creates complexity. Normally I like the second option more when creating static fields like shown in the example. But that's only my opinion / feeling :)

**Comment by aalmiray** [comment]
It looks good to me

**Comment by netopyr** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/DolphinEventBus.java, line 46 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a0mVihPMOx3Vf9Ihk:-K8a0mVihPMOx3Vf9Ihl:1289520542) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/DolphinEventBus.java#L46)):*
This should be MessageListener<? super T>

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a1_EMZUC3MnxQVnUM:-K8a1_EMZUC3MnxQVnUN:-202111032) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java#L57)):*
If I remember correctly, "mustn't" should not be used in writing.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a4oUfSfizRqBwfQks:-K8a4oUfSfizRqBwfQkt:-541571886) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java#L71)):*
Why are Message and MessageListener not typed?

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java, line 7 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a53F3CwiZ4gxtit1r:-K8a53F3CwiZ4gxtit1s:-680116383) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java#L7)):*
Should be final

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a5MuZjpMBJcvtjvht:-K8a5MuZjpMBJcvtjvhu:-1356256914) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java#L32)):*
I think we should remove the double negation

---

*[java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a6RjKeySkhsjn4OsY:-K8a6RjKeySkhsjn4OsZ:1757318367) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java#L91)):*
This needs to be corrected. We cannot rely on Thread.sleep() in our tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by aalmiray** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a6RjKeySkhsjn4OsY:-K8cYWLKlpC6yOgtf8LG:629445499) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java#L91)):*
I suggest having a look at https://github.com/jayway/awaitility

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by aalmiray** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a4oUfSfizRqBwfQks:-K8cZ2i02TmgaTt48nMq:261233237) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java#L71)):*
can't type them because the `listenersPerTopic` map can handle multiple `Topic`s with different type information

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by netopyr** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a4oUfSfizRqBwfQks:-K8cfZssOHK7wubALRiD:903673856) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java#L71)):*
In that case one could still use wildcards. Mixing raw and typed collections is usually a code smell. Either one has not tried hard enough ;) or something in the design is really broken.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by aalmiray** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a4oUfSfizRqBwfQks:-K8ch_52-Qw0tN78fptM:-68286409) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java#L71)):*
true. Which wildcard setup should be used here other than simply `<?>` (which gains you nothing IMHO).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by hendrikebbers** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/DolphinEventBus.java, line 46 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a0mVihPMOx3Vf9Ihk:-K8zPFDqgaRC-6QarvMX:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/DolphinEventBus.java#L46)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a1_EMZUC3MnxQVnUM:-K8zPHDpeuAbkjeYUgqt:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java#L57)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a4oUfSfizRqBwfQks:-K8zPI9fy1haBYADSOtg:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/Receiver.java#L71)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java, line 7 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a53F3CwiZ4gxtit1r:-K8zPIiTXPDLQbj_IZzC:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java#L7)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a5MuZjpMBJcvtjvht:-K8zPX-aZsa_KIbUpunH:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/Topic.java#L32)):*
Done.

---

*[java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a6RjKeySkhsjn4OsY:-K8zPvWifWpQpu8ZqJjq:877215236) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java#L91)):*
All other changes are committed. I will create an issue in that we can discuss the best way to test such functionality. I had a look at awaitility and it looked good to me but I want to hear Michaels thoughts about this :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by hendrikebbers** [comment]
I think this can be merged

**Comment by netopyr** [comment]
Reviewed 7 of 11 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by netopyr** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a1_EMZUC3MnxQVnUM:-K8zl4XxVGgRbKyIawc4:-1124390385) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java#L57)):*
Well, not really ;)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by hendrikebbers** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a1_EMZUC3MnxQVnUM:-K8zp_1L-gaK981ibLA8:5173019) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java#L57)):*
:P

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by hendrikebbers** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a1_EMZUC3MnxQVnUM:-K8zpfGkpUDi5H_ygyRR:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/main/java/com/canoo/dolphin/server/event/impl/DolphinEventBusImpl.java#L57)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by netopyr** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/9#-K8a6RjKeySkhsjn4OsY:-K929Juh5qH529220l1I:1637893830) ([raw file](https://github.com/canoo/dolphin-platform/blob/9dd45813211957c1f9a314789bb094886aabcf9a/java-server/src/test/java/com/canoo/dolphin/server/event/impl/TestDolphinEventBusImpl.java#L91)):*
Interesting library. I like in particular the integration with Hamcrest. Never felt the need for such a library, but I am also not against it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Comment by netopyr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/9)*

**Pull request merged**
