### PR TITLE
Java implementation of ClientConnector

### PR DESCRIPTION
**Pull request by hendrikebbers**
This PR provides a Java based implementation of the ClientConnector of Dolphin.
It introduces a general interface that is implemented by the old Groovy based implementation and a new Java based implementation. Dolphin Platform is internally based on the Java implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/200)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Preparation for #202

**Comment by blackdrag** [comment]
Reviewed 5 of 17 files at r1, 4 of 8 files at r2.
Review status: 9 of 19 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, line 37 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6DFQQzSpQW3sdH8z:-KOu6DFQQzSpQW3sdH9-:bmvqu87) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java#L37)):*
> ```Java
> @SpringApplicationConfiguration(classes = DolphinPlatformSpringTestBootstrap.class)
> @DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
> public abstract class SpringJUnitControllerTest extends AbstractJUnit4SpringContextTests implements ControllerTest {
> ```

breaks binary compatibility?

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java, line 97 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6UMMAlswriHGXCOE:-KOu6UMMAlswriHGXCOF:b8rnl8a) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java#L97)):*
> ```Java
> 
>         //Currently the event bus can not used in tests. See https://github.com/canoo/dolphin-platform/issues/196
>      //   config.getClientExecutor().submit(new Runnable() {
> ```

why the change from a lambda to an AIC?

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java, line 54 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6v9RM_dr6OnEoXT9:-KOu6v9SX-szYJ98u_vc:bnh1ufx) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java#L54)):*
> ```Java
>     }
> 
>    // @Test
> ```

why commenting out this test?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 43 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOSOXo8CZuh-lT7NS:-KOuOSOXo8CZuh-lT7NT:bnw6j9q) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L43)):*
> ```Java
> import java.util.stream.Collectors;
> 
> public abstract class AbstractConnector implements ClientConnector {
> ```

please do not remove the comments

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 86 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuAmcXsGyF6Yl6-TWs:-KOuAmcXsGyF6Yl6-TWt:bxfpgbw) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L86)):*
> ```Java
>     }
> 
>     private void processCommunication() throws InterruptedException {
> ```

why don't you split this method in multiple ones?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 123 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOoy0A0zDyxQPfvNh:-KOuOoy0A0zDyxQPfvNi:b86fjvk) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L123)):*
> ```Java
> 
>     private void handleResponseCommand(Command command) {
>         if (command instanceof DeletePresentationModelCommand) {
> ```

be aware, that if you simulate double dispatch with instanceof, you have to ensure to do it in the right order according to the hierarchy. If you migrate code to interfaces this here will break easily. If you change the hierarchy, this will easily break as well. Possible actions are making the Command classes final which is no option if a user is supposed to be able to define a custom command. Or moving this code into the command... which will surely require further changes to the code

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 267 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu9ECQO4C_bvy4nXW-:-KOu9ECQO4C_bvy4nXW0:b-vggbyk) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L267)):*
> ```Java
>         } else {
>             //TODO
>             LOG.warn("TODO");
> ```

this needs to be a severe problem, not just a warning

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy, line 349 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuDsPHBKw0ICqvFeUh:-KOuDsPI_MiVSNv5lSdi:b-keqbjk) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy#L349)):*
> ```Groovy
> 
>     /** listens for the pushListener to return. The pushListener must be set and pushEnabled must be true. */
>     public void listen() {
> ```

public is not required

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy, line 386 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuDciW68BnsvsVbeQd:-KOuDciW68BnsvsVbeQe:bojmicj) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy#L386)):*
> ```Groovy
>     boolean isPushEnabled() {
>         return this.pushEnabled;
>     }
> ```

in Groovy this is "boolean pushEnabled" in other words: just remove the "protected" from the field and you are done

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ClientConnectorPushTests.groovy, line 104 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuCQSvmUCXGN0pqrPU:-KOuCQSwv8-8HW_iPdk-:b-x72l4w) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ClientConnectorPushTests.groovy#L104)):*
> ```Groovy
>         }
>         then:
>         spoofCounter.await(2, TimeUnit.SECONDS)
> ```

why the increased wait?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/200)*

**Comment by blackdrag** [comment]
Review status: 9 of 19 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestInMemoryConfiguration.java, line 38 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuQGpd3Y1mFm5o3QKD:-KOuQGpeQIhIG4Dg_fI6:b-qbvafn) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestInMemoryConfiguration.java#L38)):*
> ```Java
>         clientDolphin.setClientModelStore(new ClientModelStore(clientDolphin));
> 
>         ClientConnector inMemoryClientConnector = new AbstractConnector(clientDolphin, threadHandler) {
> ```

why not keeping using an inMemoryClientConnector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/200)*

**Comment by hendrikebbers** [comment]
Review status: 9 of 19 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, line 37 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6DFQQzSpQW3sdH8z:-KOxW5wgfZ7rcFTidfnb:b-lbut5x) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java#L37)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> breaks binary compatibility?
</details>
What do you mean?

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java, line 97 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6UMMAlswriHGXCOE:-KOxWAd6KWlY7snpIx4f:b-bl8q1n) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinPlatformSpringTestBootstrap.java#L97)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why the change from a lambda to an AIC?
</details>
Because the server part is compiled with Java 7. Since several enterprise projects still depend on 7 we do not use Java 8 code in the server part.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestInMemoryConfiguration.java, line 38 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuQGpd3Y1mFm5o3QKD:-KOxWesjnbuQYiJNea-H:bmgt9wr) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestInMemoryConfiguration.java#L38)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why not keeping using an inMemoryClientConnector?
</details>
This changed in another pull request to:
        InMemoryClientConnector inMemoryClientConnector = new SynchronousInMemoryClientConnector(clientDolphin, serverDolphin.getServerConnector());

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java, line 54 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6v9RM_dr6OnEoXT9:-KOxWvWVpEpRbgqVjSPI:be0tiex) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java#L54)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why commenting out this test?
</details>
Because the event bus tests still not working

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 43 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOSOXo8CZuh-lT7NS:-KOxX99WEioP1-sqjfh7:b-op92ve) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L43)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> please do not remove the comments
</details>
I haven't removed any doc. This is a new class.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 86 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuAmcXsGyF6Yl6-TWs:-KOxXC6YNDuj6dgIxD3y:b-t0tz2p) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L86)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why don't you split this method in multiple ones?
</details>
This method? You mean the "handleResponseCommand", right?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 123 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOoy0A0zDyxQPfvNh:-KOxXgDiQieH878CEAj7:b-ue4mbg) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L123)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> be aware, that if you simulate double dispatch with instanceof, you have to ensure to do it in the right order according to the hierarchy. If you migrate code to interfaces this here will break easily. If you change the hierarchy, this will easily break as well. Possible actions are making the Command classes final which is no option if a user is supposed to be able to define a custom command. Or moving this code into the command... which will surely require further changes to the code
</details>
You are right. Until now the commands are still groovy code. I think we should do it when refactoring the commands to Java. I like the idea of defining concrete commands as final classes. By doing so developers could still provide specific commands by extending the non final basic class. See #228

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 267 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu9ECQO4C_bvy4nXW-:-KOxYZm71I2Q0z1aJMMM:byr4fl6) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L267)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> this needs to be a severe problem, not just a warning
</details>
Right!

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy, line 349 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuDsPHBKw0ICqvFeUh:-KOxYrio0TNMO84ReFEK:b-vtz33f) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy#L349)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> public is not required
</details>
Since we will refactor this to Java I think the public os ok.

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy, line 386 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuDciW68BnsvsVbeQd:-KOxYyivc6LhC6lzdA_T:b-c2dl17) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.groovy#L386)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> in Groovy this is "boolean pushEnabled" in other words: just remove the "protected" from the field and you are done
</details>
Since we will refactor this to Java I think the change is ok. Or do you see any problems?

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ClientConnectorPushTests.groovy, line 104 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuCQSvmUCXGN0pqrPU:-KOxZMZBpALswa7iD4MS:b-q7s0jv) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ClientConnectorPushTests.groovy#L104)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why the increased wait?
</details>
Test breaks on Travis sometime. I think the complete test is a problem but until I haven't looked into it I just changed the wait to make it work on Travis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/200)*

**Comment by aalmiray** [comment]
I think this change is too risky for 0.8.7. Please keep it for 0.9.0

**Comment by hendrikebbers** [comment]
I do not think so. We need a lot of changes in the connector when we create the new event bus. Since the event bus is planed for 0.8.8 we should better do this now.

**Comment by aalmiray** [comment]
Then I prefer if the changes needed for the event bus are done in the Groovy version first. That way you'll be sure where to look in case something breaks. Changing the base impl _and_ add more behavior later is a risky gamble IMHO

**Comment by blackdrag** [comment]
Reviewed 2 of 17 files at r1, 2 of 8 files at r2, 1 of 2 files at r3.
Review status: 14 of 19 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, line 37 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOu6DFQQzSpQW3sdH8z:-KOxpK7P2-I1XGW4Pmgf:b8zd7dg) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java#L37)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> What do you mean?
</details>
yeah, sorry, probably not important, since the usage of the class is never standalone

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 43 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOSOXo8CZuh-lT7NS:-KPT6GmSnnDI67QCDRDw:b-5ex1fz) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L43)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> I haven't removed any doc. This is a new class.
</details>
which means there are now 2 AbstractClientConnector classes, one com.canoo.dolphin.client.AbstractClientConnector and one in org.opendolphin.core.client.comm.AbstractClientConnector and if this is just a migration from Groovy to Java I would not have expected a new class to appear, In the review it is now very very difficult to see which AbstractClientConnector you actually refer to. This class here is clearly based on org.opendolphin.core.client.comm.ClientConnector in the original open doplhin. So it is not only two classes of the same name, they do a similar job as well. How can you be sure your tests will apply to this class, if they use the more or less unchanged class instead?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 123 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KOuOoy0A0zDyxQPfvNh:-KPTE7jPae_Uhrdgo4HX:b5rzgnw) ([raw file](https://github.com/canoo/dolphin-platform/blob/eff9dc96818e6d9f1efab22855e96d5e98d95b28/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L123)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> You are right. Until now the commands are still groovy code. I think we should do it when refactoring the commands to Java. I like the idea of defining concrete commands as final classes. By doing so developers could still provide specific commands by extending the non final basic class. See #228
</details>
If they do that with this code, then they will get into the IllegalArgumentException. In open-dolhin all you have to do is to define a new handle method, which will use your new command class and the Groovy dispatch mechanism will take care of the rest. Since you do a multimethods unaware double dispatch, you do not have that option. In the end you totally block the path for new commands. If you want an easy solution, base this on ScriptBytecodeAdapter.invoke to do the double dispatch for you. This multimethod logic is also the reason why there was no @CompileStatic for this code in open-dolphin.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 76 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPT8tvT5DOQvwTB0SIl:-KPT8tvT5DOQvwTB0SIm:b2ndyre) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L76)):*
> ```Java
>                     processCommunication();
>                 } catch (InterruptedException e) {
>                     //Looks like I was kiled...
> ```

and if you had been killed, you can just continue the loop? I would have expected to see at least a "break;" here... or running.set(false);

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 86 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPT9qLS5n8tOrhqJmHd:-KPT9qLS5n8tOrhqJmHe:b-kb9std) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L86)):*
> ```Java
>     }
> 
>     private void processCommunication() throws InterruptedException {
> ```

In the open dolphin client connector this was basically startCommandProcessing and a protected method, giving you the ability to overwrite this. This is not the case here. Why not?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 90 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTABrOb9KrF8K4OOkl:-KPTABrOb9KrF8K4OOkm:b7suam4) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L90)):*
> ```Java
>         List<Command> commands = toProcess.stream().map(t -> t.getCommand()).collect(Collectors.toList());
> 
>         LOG.trace("Sending batch of size {0}", commands.size());
> ```

why did you remove the "C:" in the log statements here? It was easy to filter out server and client logs using this before

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 103 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTBfkcNEaJK3vIMajl:-KPTBfkcNEaJK3vIMajm:bgz9jzk) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L103)):*
> ```Java
> 
>         uiThreadHandler.executeInsideUiThread(() -> {
>             processResults(answer, toProcess);
> ```

how does this uiThreadHandler treat exceptions produced during processResults? Because the open dolphin ClientConnector did have logic for this.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 120 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTCxv8-4xDS1MmhEMJ:-KPTCxv8-4xDS1MmhEMK:b-stm5dw) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L120)):*
> ```Java
>             }
>         });
>     }
> ```

I do spot here some differences in the logic compared to what is in open-dolphin ClientConnector. For example onFinished here always gets an empty list, while in the open-dolphin it gets a list of the involved presentation models. Why the reduction of actions the onFnished handler can do? And of course onFinishedData is completely missing here (or did it get removed in open dolphin as well?).

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 145 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTG5JsEjd3K2p2xsGY:-KPTG5JtwlhjwYJfY5EF:b-ovgx1v) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L145)):*
> ```Java
>                         Optional.ofNullable(attr.get("tag")).map(t -> {
>                             if (t instanceof Tag) {
>                                 return (Tag) t;
> ```

from the looks of it in the old code tag was always a string and never a Tag or a String. Why can it suddenly be a Tag?

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 174 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTHD0DuOYXWAxn6IhB:-KPTHD0DuOYXWAxn6IhC:b-bsuw32) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L174)):*
> ```Java
>             Optional oldVal = Optional.ofNullable(attribute.getValue());
>             Optional newVal = Optional.ofNullable(serverCommand.getNewValue());
>             if ((!oldVal.isPresent() && newVal.isPresent()) || (oldVal.isPresent() && !newVal.isPresent()) || (oldVal.isPresent() && newVal.isPresent() && !oldVal.get().equals(newVal.get()))) {
> ```

I can only assume this is supposed to represent strictMode=false. Which means I set the attribute only if the values differ which means to me: !oldVal.equals(newVal).  Optional will take care of the unwrapping of equals

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 200 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTJcPFrB4feBcasQAu:-KPTJcPGOy7qs_eLNYjY:bz79eb3) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L200)):*
> ```Java
>                 if (copies != null && !copies.isEmpty()) {
>                     if (null == serverCommand.getNewValue()) {
>                         attribute.setValue(copies.get(0).getValue());
> ```

in the groovy code the value was set only if the the entry in the copies list is not null.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 251 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTKlmoH7C9iajNnrD6:-KPTKlmoH7C9iajNnrD7:b-7c6nsu) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L251)):*
> ```Java
>             ClientAttribute attribute = getClientModelStore().findAttributeById(serverCommand.getAttributeId());
>             if (attribute != null && serverCommand.getMetadataName() != null) {
>                 if (serverCommand.getMetadataName().equals(Attribute.BASE_VALUE)) {
> ```

I think this is the wrong place to do this kind of logic.... unless you are sure there is never ever going to be any different attribute type. In the old code setAt would have handled this1

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java, line 290 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/200#-KPTLVkrbTW03wMFhUHy:-KPTLVkrbTW03wMFhUHz:b44tvvw) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c0f7454c7887e4af99893322855be9458d91760/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/AbstractConnector.java#L290)):*
> ```Java
>         }
>         waiting.set(false); // release is under way
>         releaseHandler.submit(() -> {
> ```

the withPool in the old code did potentially use more than one thread to call transmit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/200)*

**Pull request merged**
