### PR TITLE
Some preparation for Controller Testing

### PR DESCRIPTION
**Pull request by hendrikebbers**
Some code that prepares the server API for controller testing

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/85)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@aalmiray I removed the test module as a first step. I think #99 should be reviewed before this one since it contains more concrete changes of the private server API. Once both are merged (hopefully 0.8.2) we can continue work on testing, lifecycle listens etc.

**Comment by aalmiray** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 45 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvN-SEKbtJ1ehIN1p9:-KAvN-SEKbtJ1ehIN1pA:1872276810) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L45)):*
what's the point of defining these fields here? Their values are identical to existing constants. Use static imports instead if you don't like long qualified names

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNRbSqnPAGkjw8-QN:-KAvNRbSqnPAGkjw8-QO:1752002078) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L91)):*
the newly added `DolphinFactory` creates everything without using the variables defined just above this call. Either honor the previous values (pass them to `create()`)  or remove the previous 4 lines

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNkRp3W_jIR9olzc8:-KAvNkRp3W_jIR9olzc9:248070884) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L57)):*
there's no way to supply a different implementation here. Pass an instance of `OpenDolphinFactory` to the constructor instead.
Also, the name `OpenDolphinFactory` is weird considering there's no other mention of `Open` in the OpenDolphin library other than it's name alone. (granted, the name OpenDolphin is also weird as it delivers the notion of a closed one).

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/OpenDolphinFactory.java, line 8 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOEYI2wVeRTa0mvYJ:-KAvOEYJLL0UpD90rZUx:-1126079182) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/OpenDolphinFactory.java#L8)):*
see comments above. also, file headers

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOUbz3DRs89Rr2vzy:-KAvOUc-l3HTt9R-0hIU:1511817824) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L49)):*
how many URLs may be returned in a medium sized application? could this be a performance bottleneck down the road?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/85)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 45 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvN-SEKbtJ1ehIN1p9:-KBK2tH8vXggV5CCYD1_:676635175) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L45)):*
Done

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 91 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNRbSqnPAGkjw8-QN:-KBK3FJYL60aUFI5SAST:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L91)):*
done

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNkRp3W_jIR9olzc8:-KBK3IT9ArtFnVz6GH3z:408189887) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L57)):*
As a next step DolphinContextHandler will be refactored. Currently it's a singleton. The plan is to create a config class that can be passed to the constructor.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/OpenDolphinFactory.java, line 8 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOEYI2wVeRTa0mvYJ:-KBK3XfByBMfBBDbaGIm:676635175) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/OpenDolphinFactory.java#L8)):*
Done

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOUbz3DRs89Rr2vzy:-KBK3cGf3okVCaWO-MC6:343217852) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L49)):*
That's a good question. Once we have a configuration on the server we could add some configuration for the scanner in a future step. Currently we can only do a complete scan.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/85)*

**Comment by hendrikebbers** [comment]
@aalmiray merged the master in this branch after all the other pull requests were merged. Maybe you can have a last look before we merge this one.

**Comment by aalmiray** [comment]
Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 51 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KBsttfxKwbk88J27asL:-KBsttfxKwbk88J27asM:1712408774) ([raw file](https://github.com/canoo/dolphin-platform/blob/7deec18c15c2ca614fa492fe71216869197c6727/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L51)):*
previously you used `WebApplicationContext.SCOPE_SESSION` now you're using a string literal. Any particular reason to not use the constant value directly?

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java, line 33 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KBsuBOUtHm5TYupTJqq:-KBsuBOUtHm5TYupTJqr:147683444) ([raw file](https://github.com/canoo/dolphin-platform/blob/7deec18c15c2ca614fa492fe71216869197c6727/java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java#L33)):*
I find the name `OptimizedJsonCodec` a bit misleading. Is it optimizing space? speed? memory usage?

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNkRp3W_jIR9olzc8:-KBsuX9jugeNHK8LxGpi:-1213887703) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L57)):*
is there a ticket for this item?

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOUbz3DRs89Rr2vzy:-KBsukyG6M2HDJONeUv_:-1612042808) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L49)):*
This looks sketchy too me. Wouldn't this code return entries for all classes and resources in the classpath? I'd rather prfer a `ServiceLocator` or some other mean to restrict the search.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/85)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 51 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KBsttfxKwbk88J27asL:-KBt2iKT3PUxc1qysy7n:-246701819) ([raw file](https://github.com/canoo/dolphin-platform/blob/7deec18c15c2ca614fa492fe71216869197c6727/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L51)):*
No, I think that was removed by merging the master in the branch. Changed it.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java, line 33 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KBsuBOUtHm5TYupTJqq:-KBt2niIdeHohSNXmDpe:-1307645868) ([raw file](https://github.com/canoo/dolphin-platform/blob/7deec18c15c2ca614fa492fe71216869197c6727/java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java#L33)):*
Ask Michael :)

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvNkRp3W_jIR9olzc8:-KBt3JuomVERp1y_B3W4:1168881735) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L57)):*
https://github.com/canoo/dolphin-platform/issues/120

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KAvOUbz3DRs89Rr2vzy:-KBt3L6nQRUk7iTAx7jo:-849743578) ([raw file](https://github.com/canoo/dolphin-platform/blob/1943230b5e5e4366f2b1e20577a01254293b7271/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L49)):*
Mmh, I don't think that a ServiceLocator will be a good idea. By doing so all controller classes need to implement a marker interface and an application developer need to add them all to a services file. Currently this is more like Spring injection or CDI. Both scan the complete class path to find all injectable beans. 
But yes, currently this code will return entries for all classes in the class path. In an big application this could take some time but until now it's fast in all applications. Once we have a configuration for the sever we can define basic packages that should be scanned. Currently the basic package is an empty string and therefore the complete classpath will be scanned. But again: Spring and JavaEE are doing the same ;)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/85)*

**Comment by hendrikebbers** [comment]
@aalmiray wow that was a fast response :) THX
I added some answers. If you don''t have any additional feedback / points to discuss I will merge this tomorrow.

**Comment by netopyr** [comment]
Review status: 9 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java, line 33 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/85#-KBsuBOUtHm5TYupTJqq:-KBv2LhJpLPvShu8DE_G:-566279361) ([raw file](https://github.com/canoo/dolphin-platform/blob/7deec18c15c2ca614fa492fe71216869197c6727/java-server/src/main/java/com/canoo/dolphin/server/context/DefaultOpenDolphinFactory.java#L33)):*
yes :P

The primary goal is to have a Codec that is optimized for the specific needs of the Dolphin Platform, which are different from a general purpose Codec.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/85)*

**Pull request merged**
