### PR TITLE
use URL instead of String in Java Client

### PR DESCRIPTION
**Pull request by akki1306**
Currently in java client server URL is passed as String. Changed the String type to URL.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/254)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoClient.java, line 49 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/254#-KQPiA9CARx_lru4cKCb:-KQPiA9CARx_lru4cKCc:b-pn6ok7) ([raw file](https://github.com/canoo/dolphin-platform/blob/f34e340f384e642b47812768ca494353501992ef/platform-examples/todo-example/todo-client/src/main/java/com/canoo/dolphin/todo/client/ToDoClient.java#L49)):*
> ```Java
>             throw new RuntimeException("Exception while creating URL", e);
>         }
>         return url;
> ```

See comment for DolphinPlatformApplication

---

*[platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, line 68 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/254#-KQPhjEczIe1WxpRsVHJ:-KQPhjEdG371uMl9XVnn:bixywyr) ([raw file](https://github.com/canoo/dolphin-platform/blob/f34e340f384e642b47812768ca494353501992ef/platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java#L68)):*
> ```Java
>      * @return the server url
>      */
>     protected abstract URL getServerEndpoint();
> ```

Maybe this method should throw MalformedURLException. By doing so a implementation will be much easier:

return  new URL("http://localhost:8080/todo-app/dolphin");

instead of 

try {
            return new URL("http://localhost:8080/todo-app/dolphin");
   } catch (MalformedURLException e) {
            throw new RuntimeException("Exception while creating URL", e);
  }

The exception can than be handled directly in the DolphinPlatformApplication class and a developer do not need to handle it.

---

*[platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinPlatformHttpClientConnector.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/254#-KQPiVurbTruiuTd4KFV:-KQPiVurbTruiuTd4KFW:byq3nmm) ([raw file](https://github.com/canoo/dolphin-platform/blob/f34e340f384e642b47812768ca494353501992ef/platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinPlatformHttpClientConnector.java#L32)):*
> ```Java
> 
>     @Test
>     public void testSimpleCall() throws MalformedURLException {
> ```

Please make a simple helper method for all the tests that returns a dummy url and handed the MalformedURLException instead of adding the throws... to each test methods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/254)*

**Comment by hendrikebbers** [comment]
Review done. Added some comments

**Comment by akki1306** [comment]
implemented code review comments

**Comment by hendrikebbers** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java, line 66 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/254#-KQQ-mfFAJ_aCARPCsWO:-KQQ-mfGUbhNdeeiE71z:ba2xhe2) ([raw file](https://github.com/canoo/dolphin-platform/blob/e1cbd25eabc4d1f90576c731cc361bc3edf7faff/platform/dolphin-platform-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/DolphinPlatformApplication.java#L66)):*
> ```Java
>             configuration = new JavaFXConfiguration(getServerEndpoint());
>         } catch (MalformedURLException e) {
>             throw new RuntimeException("Malformed URL exception while creating configuration", e);
> ```

I think ClientInitializationException will work better here. We try to avoid using raw Runtime exceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/254)*

**Comment by hendrikebbers** [comment]
@akki1306 one last small change :)

**Comment by hendrikebbers** [comment]
Merged. THX!

**Pull request merged**
