### PR TITLE
Presentation Model Garbage Collection

### PR DESCRIPTION
**Pull request by hendrikebbers**
A first version of a garbage collection for presentation models. 
The new package that contains the gc isn't referenced in the sources and this request is done for a public review of the gc.

This package contains a first garbage collection implementation for the Dolphin Platform model. As defined by `@DolphinModel` and `@DolphinBean` each Dolphin Platform model is a hierarchy of several Dolphin Platform beans. All the beans will automatically be synchronized between server and client. To do so the remoting layer holds a representation of each Dolphin Platform Bean.
When the server controller removes a bean out of the hierarchy the garbage collection should notice this and automatically remove the bean representation from the remoting layer. By doing so the bean will automatically be deleted on the client.
How a bean can be created and removed is defined by the `BeanManager`. By using the garbage collection an application developer doesn't need to call `BeanManager.remove(...)` anymore.
The current version of the garbage collections don't allow cycles in references.

Some information how the current implementation is working:
The `GarbageCollection` class is the central point of this implementation. The class provides some methods that must called by the platform whenever a change in the beans has been done:
* `onBeanCreated(...)` must be called for each new bean
* `onPropertyValueChanged(...)` must be called whenever the internal value of a `Property` changes
* `onAddedToList(...)`must be called whenever a new item was added to an `ObservableList`
* `onRemovedFromList(...)`must be called whenever a item was removed from an `ObservableList`

This methods can simply be called be the `BeanManager`, the `PropertyImpl` and the `ObservableArrayList`. Whenever any of the methods is called the gc checks if the modified bean is still referenced by a root bean (the model of a MVC group). This is internally done by reference counting. If the bean isn't referenced anymore it will be added to a "toRemove" list. It will be removed from this list if it will be referenced again.

Whenever the `gc()` method of the garbage collection is called all the presentation models that are in the "toRemove" list will be removed. The plan is to call this method at the end of each server cycle. This means that whenever a command was handled on the server the server will remove unreferenced beans from the presentation model.

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/63)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java, line 3 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2N9RpObGKzwlVj0s:-KCa2N9RpObGKzwlVj0t:-1577569188) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java#L3)):*
why is this import needed in this code change?

---

*[java-core/src/main/java/com/canoo/dolphin/impl/IdentitySet.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2ROgrh21xFv_D3Uz:-KCa2ROgrh21xFv_D3V-:1739035329) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-core/src/main/java/com/canoo/dolphin/impl/IdentitySet.java#L1)):*
file header. *sigh* https://github.com/canoo/dolphin-platform/issues/108

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 33 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2jLRcDRQz7e-Cm0q:-KCa2jLSSgTiE3p7Tob3:547658823) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L33)):*
s/MVG/MVC/

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 50 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa3L_T9jQzlpcwdluc:-KCa3L_T9jQzlpcwdlud:-1366201904) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L50)):*
s/onRemove/onRemoveCallback/ or some other name. calling `onRemove.onRemove(arg)` looks weird

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 76 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa32cIHR-lc3tpNOSJ:-KCa32cIHR-lc3tpNOSK:-350749041) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L76)):*
use a more specific exception

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java, line 3 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2N9RpObGKzwlVj0s:-KCf4Si0nKXSI43uYN9J:-2038369736) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXBinderTest.java#L3)):*
I moved the MockedProperty class since it's now used on server and client

---

*[java-core/src/main/java/com/canoo/dolphin/impl/IdentitySet.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2ROgrh21xFv_D3Uz:-KCf4f5e5nJZokhXHtMh:589556197) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-core/src/main/java/com/canoo/dolphin/impl/IdentitySet.java#L1)):*
Done, and yes I know :( Hope to find some time for this general infrastructure issues in future. But based on the projects that depend on DP other issues currently have a bigger importance.

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 33 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa2jLRcDRQz7e-Cm0q:-KCf4z1Rmf7LQ3R29fZv:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L33)):*
done

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 50 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa3L_T9jQzlpcwdluc:-KCf5CfV--cZLQ9ExCcD:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L50)):*
done

---

*[java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 76 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KCa32cIHR-lc3tpNOSJ:-KCf5t-Mlf6V5K9uaeAU:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/0b2dc45f1cb67ff762b9489ddf7457bbdd2d885a/java-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L76)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
@netopyr maybe you find some time for a review. I would love to add this basic API in near future. Based on this we can discuss the general integration.

**Comment by moschkom** [comment]
Are Listeners on DolphinProperties automatically unsubscribed when the Presentation Model is removed?

**Comment by hendrikebbers** [comment]
I need to check / think about this. Maybe there are some constellations that currently don't work.

**Comment by hendrikebbers** [comment]
Normally you don't need to unsubscribe the listeners since you don't use the property anymore. Based on this the property instance will be GC by the JVM and since the property should be the only place that has a reference to the listener it should be removed (by GC), too.

**Comment by hendrikebbers** [comment]
I updated this branch based on the new structure (merged master) and already added the GC to DP. I added a feature flag that defines if GC should be used. By default GC is not used but it can be simply activated in the dolphin.properties file. I think we should review and merge this branch for the next release. In that case we can test the GC internally.

**Comment by aalmiray** [comment]
Reviewed 40 of 65 files at r3, 2 of 3 files at r4, 20 of 20 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanBuilderImpl.java, line 53 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZsxYGf4FjGl6anfoO:-KHZsxYGf4FjGl6anfoP:-961515538) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanBuilderImpl.java#L53)):*
> ```Java
> 
>     protected Property create(final Attribute attribute, final PropertyInfo propertyInfo) {
>         return new PropertyImpl<>(attribute, propertyInfo);
> ```

would it make sense to obtain this instance using a factory?

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java, line 38 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZtUf81dlfB2cyqr5z:-KHZtUf9ALRL9-fO2lnF:-1324122894) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java#L38)):*
> ```Java
>     String DESTROY_CONTEXT_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + "disconnectClientContext";
> 
>     String GARBAGE_COLLECTION_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + "garbage-collection";
> ```

this name has a hyphen `-` whereas the others use camel case.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java, line 106 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZtj0zVIGUXvsmFLNP:-KHZtj0zVIGUXvsmFLNQ:367123470) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java#L106)):*
> ```Java
>     }
> 
>     protected void notifyInternalListeners(ValueChangeEvent<T> event) {
> ```

is this method needed at all?

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 99 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZu29s-xwQuuMzWyEJ:-KHZu29s-xwQuuMzWyEK:-1520517747) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L99)):*
> ```Java
>     private final DolphinSession dolphinSession;
> 
>     private final GarbageCollection garbageCollection;
> ```

perhaps it's me but I find the name of this class a bit strange. The act/operation is "garbage collection" performed by a "garbage collector"

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanBuilder.java, line 25 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZu_kHa_v2ISiFrQBn:-KHZu_kHa_v2ISiFrQBo:531302263) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanBuilder.java#L25)):*
> ```Java
> public interface ServerBeanBuilder extends BeanBuilder {
> 
>    <T> T createRootModel(Class<T> beanClass);
> ```

missing javadoc

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanRepository.java, line 25 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZv6JbQV0Foa-hanje:-KHZv6JbQV0Foa-hanjf:965903977) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanRepository.java#L25)):*
> ```Java
> public interface ServerBeanRepository extends BeanRepository {
> 
>     <T> void deleteByGC(T bean);
> ```

missing javadoc. needs a better name perhaps

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java, line 64 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvZx8NhYqvWlB8BVq:-KHZvZx8NhYqvWlB8BVr:-918619699) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollection.java#L64)):*
> ```Java
>     public GarbageCollection(GarbageCollectionCallback onRemoveCallback) {
>         this.onRemoveCallback = Assert.requireNonNull(onRemoveCallback, "onRemoveCallback");
>         removeOnGC = new IdentityHashMap<>();
> ```

assignment could be made at the same time as field definition

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java, line 41 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvlS2u394zUJ4G9Vo:-KHZvlS2u394zUJ4G9Vp:-1055629952) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java#L41)):*
> ```Java
>         DolphinSession session = dolphinSessionRef.get();
>         if(session == null) {
>             throw new RuntimeException("Session == null");
> ```

throw NPE, ISE, IAE, or a DP exception instead. Or use `Assert.requireNonNull`too

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java, line 49 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvqmpykLIX167f9t3:-KHZvqmpykLIX167f9t4:-1055629952) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java#L49)):*
> ```Java
>         GarbageCollection garbageCollection = garbageCollectionRef.get();
>         if(garbageCollection == null) {
>             throw new RuntimeException("GarbageCollection == null");
> ```

throw NPE, ISE, IAE, or a DP exception instead. Or use `Assert.requireNonNull`too

---

*[platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java, line 54 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZwIxl5Bj04OWS3VYq:-KHZwIxl5Bj04OWS3VYr:-1479322278) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java#L54)):*
> ```Java
>         assertEquals(garbageCollection.getManagedInstancesCount(), 1);
>         garbageCollection.gc();
>         assertThat(removedObjects, Matchers.hasSize(0));
> ```

the code reads better if you use static imports in the case of assertions such as this one

---

*[platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java, line 849 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZwf13kyN-Jm1BXB5g:-KHZwf13kyN-Jm1BXB5h:838876356) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java#L849)):*
> ```Java
>     private GarbageCollection createGarbageCollection(GarbageCollectionCallback gcConsumer) {
>         UnstableFeatureFlags.setUseGc(true);
>         return new GarbageCollection(gcConsumer);
> ```

does the test turns this feature off at some point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java, line 38 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZtUf81dlfB2cyqr5z:-KHdRzgo6-XojSVzGXrI:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PlatformConstants.java#L38)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> this name has a hyphen `-` whereas the others use camel case.</details>
done

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java, line 106 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZtj0zVIGUXvsmFLNP:-KHdS5guo6XEv2U9-aZb:-1944317257) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/PropertyImpl.java#L106)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> is this method needed at all?</details>
yes, it's overwritten when a new property gets created. Same mechanism is already used by the observable lists

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 99 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZu29s-xwQuuMzWyEJ:-KHdSZpevma88luA_myV:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L99)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> perhaps it's me but I find the name of this class a bit strange. The act/operation is "garbage collection" performed by a "garbage collector"</details>
done

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanBuilder.java, line 25 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZu_kHa_v2ISiFrQBn:-KHdT7ViF_p0dSf1qRm8:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanBuilder.java#L25)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> missing javadoc</details>
done

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanRepository.java, line 25 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZv6JbQV0Foa-hanje:-KHdUYZYMabf0QtuAbwW:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/ServerBeanRepository.java#L25)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> missing javadoc. needs a better name perhaps</details>
done

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java, line 41 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvlS2u394zUJ4G9Vo:-KHdUmTcpF-8vTpEOfsv:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java#L41)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> throw NPE, ISE, IAE, or a DP exception instead. Or use `Assert.requireNonNull`too</details>
done

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java, line 49 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvqmpykLIX167f9t3:-KHdUn2m_uUh5CcNJ5Id:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/mbean/beans/DolphinSessionInfo.java#L49)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> throw NPE, ISE, IAE, or a DP exception instead. Or use `Assert.requireNonNull`too</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
Review status: 27 of 45 files reviewed at latest revision, 11 unresolved discussions.

---

*[platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanBuilderImpl.java, line 53 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZsxYGf4FjGl6anfoO:-KHdW7nluG7QgVCNZBXp:-221952000) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanBuilderImpl.java#L53)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> would it make sense to obtain this instance using a factory?</details>
I don't think so. This class defines does nothing than create the concrete property / list instances. Currently there is no other way than creating this objects. It would make sense if there is another remoting lib next to OD. 

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollector.java, line 64 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZvZx8NhYqvWlB8BVq:-KHdWouc2Wzvife4hw8O:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/impl/gc/GarbageCollector.java#L64)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> assignment could be made at the same time as field definition</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
Review status: 27 of 45 files reviewed at latest revision, 11 unresolved discussions.

---

*[platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java, line 54 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZwIxl5Bj04OWS3VYq:-KHdY_P3-7RXYr9XRgZp:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java#L54)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> the code reads better if you use static imports in the case of assertions such as this one</details>
done

---

*[platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java, line 849 \[r5\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/63#-KHZwf13kyN-Jm1BXB5g:-KHdZHmMBdjxUIXC631v:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/6f4253d9bb32e551450a842db6ea0b4b1ee5bb13/platform/dolphin-platform-server/src/test/java/com/canoo/dolphin/server/impl/gc/TestGarbageCollection.java#L849)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> does the test turns this feature off at some point?</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/63)*

**Comment by hendrikebbers** [comment]
refactored the branch based on @aalmiray review. I think the request is ready to merge. Don't know if we should do this before or after the OD merge? @aalmiray ?

**Comment by aalmiray** [comment]
it should be merged after the OD PR is taken in

**Pull request merged**
