### PR TITLE
Dolphin Session & Client Scope

### PR DESCRIPTION
**Pull request by hendrikebbers**
This pull request introduces 3 new parts:

The DolphinSession (Interface) is new part of the public API and can be injected in any controller:

@Inject
DolphinSession dolphinSession

It represents the public API for a Dolphin Platform context and provides similar methods than the session context. Currently each session will contain exactly 1 Dolphin Platform context / DolphinSession but this will change in future (1 DolphinSession for each Tab in a Browser). So instead of using the session context to store and manage data developers should use the DolphinSession.

Based on the Dolphin Platform context / the DolphinSession a new scope was added to Spring that is currently called ClientScope. This can easily be used to define injectable Spring beans that lifecycle is bound to a Dolphin Platform Context:

@ClientScoped
public class MyService() { ... }

Based on the Dolphin Platform context / the DolphinSession a new scope was added to JavaEE / CDI that is currently called ClientScope. This can easily be used to define injectable Spring beans that lifecycle is bound to a Dolphin Platform Context:

@ClientScoped
public class MyService() { ... }

Since the Dolphin Platform context / the DolphinSession is still bound to a session (but will change in future) the lifecycles of the new scopes are equal to the SessionScope.

This new feature are still missing unit tests but currently this can't be tested since the DolphinContextHandler is still a singleton. This will be refactored in my next Pull Request. Once this is done We can create unitTests for the new features.

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/121)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/ClientScopeContext.java, line 79 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa0tu6Vpb-t3I-2qrR:-KCa0tu6Vpb-t3I-2qrS:117006686) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/ClientScopeContext.java#L79)):*
synchronized map or concurrent hash map?

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1HP4Kz1TRnuVgJRx:-KCa1HP4Kz1TRnuVgJRy:672655474) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L19)):*
spurious import? I don't see any new code that makes use of this import statement

---

*[java-server/src/main/java/com/canoo/dolphin/server/DolphinSession.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1RhWDklQUT-GCh_U:-KCa1RhWDklQUT-GCh_V:121056264) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server/src/main/java/com/canoo/dolphin/server/DolphinSession.java#L22)):*
does it make sense to expose a method that returns a `Set` of keys? Even an `attributeSet` method akin to `java.util.Map.entrySet`?

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionImpl.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1pELnJN3Kob7JulK:-KCa1pELnJN3Kob7JulL:-622752326) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionImpl.java#L32)):*
wouldn't `ConcurrentHashMap` work better than a `synchronized` Map?  If there's no contention you'll pay a heavier price by synchronizing all the time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/121)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1HP4Kz1TRnuVgJRx:-KCf6enkGs3UHOlqZZed:496008847) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server-spring/src/main/java/com/canoo/dolphin/server/spring/DolphinPlatformSpringBootstrap.java#L19)):*
Oh, was used in the javadoc as a link. Changed this one

---

*[java-server/src/main/java/com/canoo/dolphin/server/DolphinSession.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1RhWDklQUT-GCh_U:-KCf6rr08ankYyVk3-mk:753170157) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server/src/main/java/com/canoo/dolphin/server/DolphinSession.java#L22)):*
The HttpSession interface defines "Enumeration<String> getAttributeNames()" but I think a unmodifiable Set would be better. added it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/121)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionImpl.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/121#-KCa1pELnJN3Kob7JulK:-KCf8Hd4X1HU_Jpf8DwT:1861363073) ([raw file](https://github.com/canoo/dolphin-platform/blob/1e7979c6feb24a2c11e7236908dea29980debcca/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinSessionImpl.java#L32)):*
Yes this will make sense since normally only 1 thread (thread that handles the current http request) will use it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/121)*

**Comment by hendrikebbers** [comment]
Did all needed changes based on the review. @netopyr / @aalmiray I will merge this after the meeting next week if we defined a general / final architecture definition.

**Pull request merged**
