### PR TITLE
DolphinContextHandler refactoring

### PR DESCRIPTION
**Pull request by hendrikebbers**
Until now the DolphinContextHandler and DolphinEventBus were defined as singleton. This pull requests refactores the classes and provide a way how they can simple be instantiated at Runtime and will provide a better test support

---
This change is [Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/123)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 35 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zQkh1qB1rlSCmZux:-KC_zQkh1qB1rlSCmZuy:343462020) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L35)):*
there has to be a better way than doing this `DolphinPlatformJavaeeBootstrap`and `DolphinPlatformSpringBootstrap` are still magic singletons

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zHl9hb-2KGb_keOO:-KC_zHlArLiVaRwWZEC5:-2100158562) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L71)):*
use `DolphinEventBus` type instead

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextCleaner.java, line 28 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zdp6a1EolIKXnWNr:-KC_zdp74yCwewy1P5OZ:324571281) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextCleaner.java#L28)):*
validate arguments

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 105 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zux9KosbWFOhE52B:-KC_zux9KosbWFOhE52C:1125542686) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L105)):*
throw `UnsupportedOperationException`instead

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 117 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-37Pzj4fnT0AKYtY:-KCa-37Pzj4fnT0AKYtZ:651443701) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L117)):*
we've covered this before. Either use `DolphinEventBus` (and expands its contract) or don't expose this field. Callers should know be aware that the implementation may be `DolphinEventBusImpl`.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java, line 40 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-QVrpb0bGNdYgYJR:-KCa-QVrpb0bGNdYgYJS:-215100047) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java#L40)):*
please use a more specific exception that `RuntimeException`. `IllegalStateException` is a good starting point. A DP specific exception would be better.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java, line 47 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-vef77JNiqC_DRF_:-KCa-vef77JNiqC_DRFa:-299318416) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java#L47)):*
can't this instance be injected/supplied from the outside?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/123)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java, line 71 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zHl9hb-2KGb_keOO:-KCewTLaa5wPConi2HHt:-1845069080) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContext.java#L71)):*
We currently can't do this since the event bus implementation is far from perfect. But I think it's good to do small step pull requests (DolphinContext -> DolphinContextHandler -> EventBus) instead of doing a big one that can't be reviewed or need endless to be committed. I already have a branch that contains a new implementation of the Event Bus that don't need to reference the Impl classes from the outside. Once we finished all this pull requests this will be the next big step. Therefore I would use the Impl here instead of adding private methods to the interface since it will change in near future :)

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 117 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-37Pzj4fnT0AKYtY:-KCexCFD712NMGI25rOr:624302390) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L117)):*
See the other comment about Event Bus. At the moment I would simply use the Impl here and change it in a Event Bus related Pull Request

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/123)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextCleaner.java, line 28 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zdp6a1EolIKXnWNr:-KCfpLw2LTE0isX4eCCy:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextCleaner.java#L28)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 105 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zux9KosbWFOhE52B:-KCfpka3xJzEImlMtg84:171158858) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L105)):*
Oh, I missed to implement this...

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java, line 40 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-QVrpb0bGNdYgYJR:-KCfpu6K-aAD8A0UcC-a:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java#L40)):*
Done.

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java, line 47 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KCa-vef77JNiqC_DRF_:-KCfqJJWotP7JurCkZRk:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandlerFactoryImpl.java#L47)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/123)*

**Comment by hendrikebbers** [comment]
Review status: 12 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java, line 35 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zQkh1qB1rlSCmZux:-KCfr4vS8QWPOiP56242:1085719535) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server-javaee/src/main/java/com/canoo/dolphin/server/javaee/BeanFactory.java#L35)):*
Only the DolphinPlatformBootstrap instance for JavaEE is a Magic Singleton since I have currently no Idea how can I do the bootstrap better in javaEE / CDI. I created an issue: https://github.com/canoo/dolphin-platform/issues/124

---

*[java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java, line 105 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/123#-KC_zux9KosbWFOhE52B:-KCfqwwayTuR5jcYxc8N:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/b207d7b3ca14f4d2e06928476334a44a914e1632/java-server/src/main/java/com/canoo/dolphin/server/context/DolphinContextHandler.java#L105)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/123)*

**Comment by hendrikebbers** [comment]
Did all needed changes based on the review. @netopyr / @aalmiray I will merge this after the meeting next week if we defined a general / final architecture definition.

**Comment by Dierk** [comment]
Before we call any architecture "final", Jochen and me should also contribute our points.

**Comment by hendrikebbers** [comment]
@Dierk In this case "final" stands for "final for us". I think it's good to collect / sort / finalize the ideas that @netopyr and I have before we discuss and present them it in a big group for a general discuss ;)

**Comment by Dierk** [comment]
ok, fair enough :-)

**Comment by Dierk** [comment]
Will we have a Portfolio-CRUD demo for the architecture proposal?

**Comment by hendrikebbers** [comment]
@Dierk The architecture proposal that I mentioned is more about scopes and tab support in the browser. So a Portfolio demo won't look any different before / after the changes. In general we can create a portfolio demo based on DP. I already have this on my todo list .

**Pull request merged**
