### PR TITLE
Controller scan for JBOSS based on JBOSS virtual file system (VFS)

### PR DESCRIPTION
**Pull request by hendrikebbers**
Bugfix for #78

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/79)

### CODE REVIEW

**Comment by netopyr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 56 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/79#-KAdImqI0Bin-cXCgpP5:-KAdImqJc3DvvdeKnA_9:-1521413674) ([raw file](https://github.com/canoo/dolphin-platform/blob/237d05200c51d5140741ffc6fe92ca1c6b4c8bcd/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L56)):*
If I look at the correct javadocs, configuration.getUrls() returns a Set, i.e. this check is not needed.

I would probably even try to avoid the whole loop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/79)*

**Comment by hendrikebbers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 56 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/79#-KAdImqI0Bin-cXCgpP5:-KAdLSoj2t6TnQUYgYWb:-338093161) ([raw file](https://github.com/canoo/dolphin-platform/blob/237d05200c51d5140741ffc6fe92ca1c6b4c8bcd/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L56)):*
I think you can't avoid the loop since Classloader.getResources() returns an Enumeration. 
I removed the if

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/79)*

**Comment by netopyr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 56 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/79#-KAdImqI0Bin-cXCgpP5:-KAdMSaPSk7Ze6ClpS7B:-1705042728) ([raw file](https://github.com/canoo/dolphin-platform/blob/237d05200c51d5140741ffc6fe92ca1c6b4c8bcd/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L56)):*
You could turn it into a Collection first, maybe something like:
configuration.getUrls().addAll(Collections.list(res));

But anyway, does not really matter.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/79)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java, line 56 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/79#-KAdImqI0Bin-cXCgpP5:-KAdOI6fTbY3rih2Rx4a:-1357510219) ([raw file](https://github.com/canoo/dolphin-platform/blob/237d05200c51d5140741ffc6fe92ca1c6b4c8bcd/java-server/src/main/java/com/canoo/dolphin/server/controller/ControllerRepository.java#L56)):*
Ha :) songs like a plan. Don't know that the Collection utils provide this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/79)*

**Pull request merged**
