### PR TITLE
Android Compatibility

### PR DESCRIPTION
**Pull request by hendrikebbers**
Android Client API for Dolphin Platform

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/290)

### CODE REVIEW

**Comment by timo0** [comment]
*[integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, line 52 at r8](https://reviewable.io:443/reviews/canoo/dolphin-platform/290#-Ka7nrqH395sXfY0Acl3:-Ka7nrqId4kKjMVkSvTz:bvlfn7j) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c26a03b96f19e8c42fbcc34928c56273dd9a2fc/integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java#L52)):*
> ```Java
>                     HttpURLConnection httpURLConnection = (HttpURLConnection) connection;
>                     httpURLConnection.connect();
>                     if(httpURLConnection.getResponseCode() == 200) {
> ```

Use Enum

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/290)*

**Comment by timo0** [comment]
Reviewed 7 of 23 files at r1, 10 of 13 files at r2, 10 of 11 files at r3, 10 of 14 files at r4, 1 of 2 files at r5, 8 of 11 files at r8, 1 of 5 files at r9.
Review status: 42 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/290)*

**Comment by hendrikebbers** [comment]
Review status: 42 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java, line 52 at r8](https://reviewable.io:443/reviews/canoo/dolphin-platform/290#-Ka7nrqH395sXfY0Acl3:-Ka7swy6cJx6ZLNUgpfK:b-896fix) ([raw file](https://github.com/canoo/dolphin-platform/blob/1c26a03b96f19e8c42fbcc34928c56273dd9a2fc/integration-tests/src/test/java/com/canoo/dolphin/integration/AbstractIntegrationTest.java#L52)):*
<details><summary><i>Previously, timo0 (Timo B) wrote…</i></summary><blockquote>

Use Enum
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/290)*

**Comment by timo0** [comment]
Reviewed 3 of 5 files at r9, 1 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/290)*

**Pull request merged**
