### PR TITLE
unit tests to Java syntax - PART 1

### PR DESCRIPTION
**Pull request by hendrikebbers**
Part 1 for https://github.com/canoo/dolphin-platform/issues/452

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/461)

### CODE REVIEW

**Comment by blackdrag** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 3 files at r4, 20 of 21 files at r5.
Review status: 21 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy, line 81 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-KiieUomCWf5bZ8l5mS0:-KiieUomCWf5bZ8l5mS1:bylfux2) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy#L81)):*
> assert batcher.waitingBatches.val == [list[3]]
This is not checked anymore

---

*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy, line 244 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiif6kgK0dfs0ScEB_2:-Kiif6kkfcrfjlL-W91R:b-9we76p) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy#L244)):*
> ```Groovy
>             List<CommandAndHandler> nextBatch = batcher.getWaitingBatches().getVal();
>             Assert.assertEquals(1, nextBatch.size());
>             Assert.assertEquals(GetPresentationModelCommand.class, nextBatch.get(0).getCommand().getClass());
> ```

strictly seen you check is more strict, since you do an equals for the class not "just" an instanceof

---

*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 187 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiii9Dt7oj2GGmq-F1z:-Kiii9Dt7oj2GGmq-F2-:b-wfwzfj) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L187)):*
> ```Groovy
>     void testHandle_ValueChanged_AttrNotExists() {
>         //TODO: How to convert this to Java?
>         assert !clientConnector.dispatchHandle(new ValueChangedCommand("0", "oldValue", "newValue"));
> ```

If I have seen right, then this method is void, a void-declared method returns in Groovy null. null as boolean is false. So it is possible that code has been changed and the method is now void and was not before. In that case I would remove the assert. It could also bee, that this test is there to ensure the method does not return anything, even if the signature gets changed to not be void anymore. of course the same goes for all other places with this check

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/DeletePresentationModelTests.groovy, line 102 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiil9vIbkzo8y2etUem:-Kiil9vIbkzo8y2etUen:bk5cmqj) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/DeletePresentationModelTests.groovy#L102)):*
> Assert.assertEquals(model, model);
Assert.assertEquals(model, found); ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/461)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy, line 244 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiif6kgK0dfs0ScEB_2:-KioM__8uZsU4dELT0B7:b8ioouy) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy#L244)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary><blockquote>

strictly seen you check is more strict, since you do an equals for the class not "just" an instanceof
</blockquote></details>

But I think this is fine since the class is defined exclusive for this test ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/461)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 187 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiii9Dt7oj2GGmq-F1z:-KioN4meH_3rNNipnb4k:b-ni189i) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L187)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary><blockquote>

If I have seen right, then this method is void, a void-declared method returns in Groovy null. null as boolean is false. So it is possible that code has been changed and the method is now void and was not before. In that case I would remove the assert. It could also bee, that this test is there to ensure the method does not return anything, even if the signature gets changed to not be void anymore. of course the same goes for all other places with this check
</blockquote></details>

Method is void. I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/461)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/DeletePresentationModelTests.groovy, line 102 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-Kiil9vIbkzo8y2etUem:-KioNOtlc3nCtQOjqkPP:b-n9tkgy) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/DeletePresentationModelTests.groovy#L102)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary><blockquote>

> Assert.assertEquals(model, model);
Assert.assertEquals(model, found); ?
</blockquote></details>

changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/461)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy, line 81 at r5](https://reviewable.io:443/reviews/canoo/dolphin-platform/461#-KiieUomCWf5bZ8l5mS0:-KioO7TLU0nvka4x76CB:b-l8ws6h) ([raw file](https://github.com/canoo/dolphin-platform/blob/087babd1799040eacc19a6e5b6e63a65172fae27/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/BlindCommandBatcherTest.groovy#L81)):*
This is done directly after the check:

>  try {
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>             Assert.assertEquals(Collections.singletonList(list.get(3)), batcher.getWaitingBatches().getVal());
>         } catch (InterruptedException e) {
>             e.printStackTrace();
>             Assert.fail(e.getMessage());
>         }
>     }</details>


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/461)*

**Pull request merged**
