### PR TITLE
Some Java 8 improvements

### PR DESCRIPTION
**Pull request by hendrikebbers**
Some Java 8 improvements, general refactoring

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/774)

### CODE REVIEW

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/session/ClientSessionStore.java, line 17 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qHJpgcgK8N7HmXoMx:-L-qH97G86Nfg-S1-cAp:b-45yj6j) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-client/src/main/java/com/canoo/platform/client/session/ClientSessionStore.java#L17)):*
> ```Java
>     String getClientIdentifierForUrl(URL endpoint);
> 
>     default Optional<String> clientIdentifierForUrl(final URL endpoint) {
> ```

I think you should decide for one of the two variants. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/Property.java, line 118 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qIMUrgihl1OkGomw7:-L-qIMUsbg5hMWpidiA9:b-7tdrph) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/Property.java#L118)):*
> ```Java
>     T get();
> 
>     default Optional<T> value() {
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/ValueChangeEvent.java, line 49 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qKDmHs_7GDrpMPdch:-L-qKDmHs_7GDrpMPdci:b-7tdrph) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-remoting-common/src/main/java/com/canoo/platform/remoting/ValueChangeEvent.java#L49)):*
> ```Java
> 
>     default Optional<T> oldValue() {
>         return Optional.ofNullable(getOldValue());
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-remoting-server/src/main/java/com/canoo/platform/remoting/server/event/MessageEvent.java, line 28 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qKVmt_9FMLZAVtjHT:-L-qKVmt_9FMLZAVtjHU:b-7tdrph) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-remoting-server/src/main/java/com/canoo/platform/remoting/server/event/MessageEvent.java#L28)):*
> ```Java
> 
>     default Optional<T> data() {
>         return Optional.ofNullable(getData());
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-remoting-server/src/main/java/com/canoo/platform/remoting/server/event/MessageEventContext.java, line 17 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qKbvU8elhMn-wPz-E:-L-qKbvU8elhMn-wPz-F:b-9h347) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-remoting-server/src/main/java/com/canoo/platform/remoting/server/event/MessageEventContext.java#L17)):*
> ```Java
> 
>     default Optional<Serializable> metadata(final String key) {
>         return Optional.ofNullable(getMetadata().get(key));
> ```

I think there is no need for this method. You have to be careful not to add too many convenience methods. they are nice, but they also increase the need for maintenance 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/client/ClientSession.java, line 51 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qL6-Rd6mvdAWy9SJN:-L-qL6-Rd6mvdAWy9SJO:b-7tdrph) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/client/ClientSession.java#L51)):*
> ```Java
> 
>     default <T> Optional<T> attribute(final String name) {
>         return Optional.ofNullable(getAttribute(name));
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
*[platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/spi/ServerCoreComponents.java, line 63 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qL8kz87tk7C79sNOc:-L-qL8kz87tk7C79sNOd:b-7tdrph) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-server/src/main/java/com/canoo/platform/server/spi/ServerCoreComponents.java#L63)):*
> ```Java
> 
>     default <T> Optional<T> instance(final Class<T> cls) {
>         return Optional.ofNullable(getInstance(cls));
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by blackdrag** [comment]
Reviewed 48 of 51 files at r1.
Review status: 48 of 51 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/ClientContext.java, line 59 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/774#-L-qI1rZblguFxacH-Y9:-L-qI1rZblguFxacH-YA:brkh6lm) ([raw file](https://github.com/canoo/dolphin-platform/blob/d50060a13e368711fa32d64e85d82878c4482e53/platform/dolphin-platform-remoting-client/src/main/java/com/canoo/platform/remoting/client/ClientContext.java#L59)):*
> ```Java
>     String getClientId();
> 
>     default Optional<String> clientId() {
> ```

same game... I think you should decide for one variant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/774)*

**Comment by hendrikebbers** [comment]
Based on discussion with @blackdrag we will remove the Optional methods. We will have a look how the pattern will be used in other projects.
One of the point that we discussed was for example the naming of the methods:

`Optional<T> getOptionalValue()
`
VS
`Optional<T> value()
`

**Pull request merged**
