### PR TITLE
dolphin-remoting-combined module migrated to Java

### PR DESCRIPTION
**Pull request by hendrikebbers**
All groovy classes in dolphin-emoting-combined are converted to Java

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/214)

### CODE REVIEW

**Comment by aalmiray** [comment]
I think this change is too risky for 0.8.7. Please keep it for 0.9.0

**Comment by hendrikebbers** [comment]
Changed it to 0.8.8. I think this changes are not that complexe

**Comment by hendrikebbers** [comment]
@aalmiray the module is only used for controller tests in Dolphin Platform and this tests are working fine. I do not see why we should not merge this now.

**Comment by blackdrag** [comment]
Reviewed 3 of 16 files at r1.
Review status: 3 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPSzHNwBZ5tG91rKnej:-KPSzHNxs5Bxr_zkhhg_:bryekcr) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java#L1)):*
> ```Java
> package org.opendolphin.core.client.comm;
> ```

missing license header

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java, line 20 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPSz__ZQxz_ZX3yiMpM:-KPSz__ZQxz_ZX3yiMpN:b-egsxgh) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java#L20)):*
> ```Java
>     private long sleepMillis = 0;
> 
>     private final ServerConnector serverConnector;
> ```

if you want to keep the semantics of Groovy here, there should be a getter for serverConnector

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/SynchronousInMemoryClientConnector.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-SqoMk_F13XuZESQ:-KPT-SqoMk_F13XuZESR:bryekcr) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/SynchronousInMemoryClientConnector.java#L1)):*
> ```Java
> package org.opendolphin.core.client.comm;
> ```

missing license header

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPT-cgy681f4od7bH6D:b-okes64) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
> ```Java
> public class DefaultInMemoryConfig {
> 
>     private final ClientDolphin clientDolphin;
> ```

in the Groovy code this was not final and there was a setter

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 20 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-iWfvUkfgFah3lr7:-KPT-iWfvUkfgFah3lr8:b-okes64) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L20)):*
> ```Java
>     private final ClientDolphin clientDolphin;
> 
>     private final ServerDolphin serverDolphin;
> ```

in the Groovy code this was not final and there was a setter

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0309QE06ZDHUcvq7:-KPT0309QE06ZDHUcvq8:b-bhh5ya) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L22)):*
> ```Java
>     private final ServerDolphin serverDolphin;
> 
>     private final InMemoryClientConnector clientConnector;
> ```

there was no need for this variable in the Groovy code, why is there now?

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0JvTx4kAbgKtRLEi:-KPT0JvUG8e844BWtOmq:bryekcr) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java#L1)):*
> ```Java
> package org.opendolphin.core.comm;
> ```

missing license header

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java, line 55 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0ZvY5iMKkoTNgCXj:-KPT0ZvY5iMKkoTNgCXk:b-tsfn91) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java#L55)):*
> ```Java
>      * needed since tests should run fully asynchronous but we have to wait at the end of the test
>      */
>     private CountDownLatch done = new CountDownLatch(1);
> ```

"done" was accessible in the Groovy code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPSzHNwBZ5tG91rKnej:-KPT4Ie4zGONlMo1gNBG:bb6un1j) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java#L1)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> missing license header
</details>
Done

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/SynchronousInMemoryClientConnector.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-SqoMk_F13XuZESQ:-KPT4KqB_T-L1WJxqQYD:bb6un1j) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/SynchronousInMemoryClientConnector.java#L1)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> missing license header
</details>
Done

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0JvTx4kAbgKtRLEi:-KPT4NLRl1l_hXd9J-QC:bb6un1j) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java#L1)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> missing license header
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java, line 20 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPSz__ZQxz_ZX3yiMpM:-KPT4qi8vcJFkFX65Eur:b-n9sz1e) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/client/comm/InMemoryClientConnector.java#L20)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> if you want to keep the semantics of Groovy here, there should be a getter for serverConnector
</details>
I do not think that it makes since at all since the getter is never called. Since this classes are only used internally by Dolphin Platform I do not think that we need this method.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPT5A-aXO1Zr4fFgk3r:b-bj51zd) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> in the Groovy code this was not final and there was a setter
</details>
This class is a helper class that defines a default configuration. setter for the fields were not used before and therefore I think that we should not add them.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 20 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-iWfvUkfgFah3lr7:-KPT5Ty0nzkyQGbj0saR:b-bj51zd) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L20)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> in the Groovy code this was not final and there was a setter
</details>
This class is a helper class that defines a default configuration. setter for the fields were not used before and therefore I think that we should not add them.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java, line 55 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0ZvY5iMKkoTNgCXj:-KPT5bD284COwF_2uYxQ:b-6dyanf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/TestInMemoryConfig.java#L55)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> "done" was accessible in the Groovy code
</details>
yes, but this is a unit tests. I do not think that we need to access it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0309QE06ZDHUcvq7:-KPT62MdAzgi-S3aFXGX:bygcsfb) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L22)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> there was no need for this variable in the Groovy code, why is there now?
</details>
I need it in Dolphin Platform in future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT0309QE06ZDHUcvq7:-KPT6H9ztplqMAfIBfCj:b-poftet) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L22)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> I need it in Dolphin Platform in future.
</details>
It is already used in Dolphin Platform

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by aalmiray** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPT6CC-UaIwUP7k0Ein:bcotpns) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> This class is a helper class that defines a default configuration. setter for the fields were not used before and therefore I think that we should not add them.
</details>
In Groovy code, when you define a "field" such as `ClientDolphin clientDolphin` the compiler generates a private field, a getter and a setter. This is the syntax used to tell the compiler how to identify "properties". In java this definition turns out to be package private scoped field just as it stands. Thus, as Jochen says, if you want to keep the same semantic behavior you must define a mutable private field with getter and setter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPT6u7wED6WUPGKAaU6:b-foiu2l) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> In Groovy code, when you define a "field" such as `ClientDolphin clientDolphin` the compiler generates a private field, a getter and a setter. This is the syntax used to tell the compiler how to identify "properties". In java this definition turns out to be package private scoped field just as it stands. Thus, as Jochen says, if you want to keep the same semantic behavior you must define a mutable private field with getter and setter.
</details>
You are right. I think that we do not need the same behavior here because a setter males no sense. Even in groovy this should be final. If it's more safe for you we can add there getter and remove the final. I can not see any problem by the current version, do I miss anything?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by aalmiray** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPTBMcUJ8oX3oRbSi46:b-begir5) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> You are right. I think that we do not need the same behavior here because a setter males no sense. Even in groovy this should be final. If it's more safe for you we can add there getter and remove the final. I can not see any problem by the current version, do I miss anything?
</details>
The problem is, there are two main changes that may step into each other toes. One one hand is the migration of Groovy code into Java code _retaining_ the same behavior. On the other one is removing excess code that's no longer needed due to said migration. I'd prefer if these two steps were made in two separate PRs. In this way, we can validate that the code migration retains 100% behavior compatibility, which IMHO is more important right now than trimming excess code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
Review status: 3 of 36 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java, line 18 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPT-cgy681f4od7bH6C:-KPTE326f5KZlm0kA7U0:b2q6vb4) ([raw file](https://github.com/canoo/dolphin-platform/blob/7e1bc023c304133f1e7b3b3db705fce5ca95c089/remoting/dolphin-remoting-combined/src/main/groovy/org/opendolphin/core/comm/DefaultInMemoryConfig.java#L18)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> The problem is, there are two main changes that may step into each other toes. One one hand is the migration of Groovy code into Java code _retaining_ the same behavior. On the other one is removing excess code that's no longer needed due to said migration. I'd prefer if these two steps were made in two separate PRs. In this way, we can validate that the code migration retains 100% behavior compatibility, which IMHO is more important right now than trimming excess code.
</details>
ok I will add the missing methods in this PR. We can remove them after the next release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Comment by hendrikebbers** [comment]
@blackdrag @aalmiray added the missing methods. I think we can merge it now

**Comment by aalmiray** [comment]
Did you add the missing methods on *all* changed classes?

**Comment by hendrikebbers** [comment]
@aalmiray I think so

**Comment by blackdrag** [comment]
Reviewed 2 of 16 files at r1, 22 of 24 files at r2.
Review status: 26 of 36 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/util/AbstractDolphinBasedTest.java, line 33 \[r2\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/214#-KPWmohX8kccQ_o-Fa-Y:-KPWmohYwt7LYvtUIaU-:b-exypis) ([raw file](https://github.com/canoo/dolphin-platform/blob/6c6d4ea560f5ad3c5bf599068b8017b10a16107f/platform/dolphin-platform-client/src/test/java/com/canoo/dolphin/client/util/AbstractDolphinBasedTest.java#L33)):*
> ```Java
> import com.canoo.dolphin.internal.EventDispatcher;
> import com.canoo.dolphin.internal.collections.ListMapper;
> import org.opendolphin.core.ModelStore;
> ```

why is this import needed now? If it is just from renaming ServerModelStore to ModelStore I would have expected an import being deleted in favour of this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/214)*

**Pull request merged**
