### PR TITLE
#626 move Binding interface to core module

### PR DESCRIPTION
**Pull request by Nipel-Crumple**
Hi!

It is my first pull request, I hope that I've done all in a proper way. 

Thanks for your explanation!

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/647)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Hi @Nipel-Crumple and THGX for your contribution ✌️. The interface should not only be moved to the new module but the package should change, too. The interface should be placed in the `com.canoo.platform.core.functional` package that contains all the functional interfaces that are needed by Dolphin Platform (client & server). So the module is 👍 but the package must be changed. Can you update your PR based on that info?

**Comment by Nipel-Crumple** [comment]
@hendrikebbers Thanks for your comment! Yes, I've changed package too.

**Comment by hendrikebbers** [comment]
Cool! THX @Nipel-Crumple for the contribution

**Comment by hendrikebbers** [comment]
see #626

**Pull request merged**
