### PR TITLE
Base for Server Integration Tests 

### PR DESCRIPTION
**Pull request by hendrikebbers**
Adds a module for integration tests that can start several containers (Payara, TomEE, ...) with a deployed Dolphin Platform application by using docker and run tests against the app.

Currently Payara is working and this approach runs at my local machine and at Travis. This PR is to discuss the approach and how it is defined in gradle since I think there is some refactoring needed :)

---

This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/235)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 10 of 19 files at r1, 4 of 10 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KUzzQu0EH6vwmS-3Ui4:b-2x0s7d) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
> ```Gradle
>     apply plugin: 'idea'
>     apply plugin: 'com.github.ben-manes.versions'
>     apply plugin: 'groovy'
> ```

this applies the `groovy` plugin to all projects. Do you really need to do this?

---

*[buildSrc/src/main/groovy/ExecWait.groovy, line 1 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzvOnbs5G16QYxiMn:-KUzzvOnbs5G16QYxiMo:b78jg48) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/buildSrc/src/main/groovy/ExecWait.groovy#L1)):*
> ```Groovy
> import org.gradle.api.DefaultTask
> ```

missing license header. All source code must have a license header.

---

*[integration-tests/integration-tests.gradle, line 14 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--eKFxmrNqiWIZDTT:-KV--eKFxmrNqiWIZDTU:b-htwr2z) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/integration-tests.gradle#L14)):*
> ```Gradle
> //Base Java Image
> 
> task copyWarForPayaraIntegrationImage(type: Exec) {
> ```

have a look at `https://github.com/avast/docker-compose-gradle-plugin`

---

*[integration-tests/docker-base/payara-integration/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--q5XDroyyfr9YCY4:-KV--q5XDroyyfr9YCY5:b-hxambf) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/docker-base/payara-integration/Dockerfile#L3)):*
> ```Dockerfile
> FROM airhacks/payara-configured
> MAINTAINER Adam Bien, adam-bien.com
> # For more information about ping see: https://github.com/AdamBien/ping/
> ```

what does ping have to do here?

---

*[integration-tests/docker-base/payara-integration/todo-app.war, line 0 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--6vw9ZqEPPq8maZd:-KV--6vx2sNm5-esJ-nn:b-2983sw) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/docker-base/payara-integration/todo-app.war#L0)):*
should this binary be checked in or should it be grabbed from a previous build step?

---

*[integration-tests/docker-base/tomee-integration/Dockerfile, line 2 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--wCbC0oP-Qzs8JoI:-KV--wCbC0oP-Qzs8JoJ:buwn1bg) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/docker-base/tomee-integration/Dockerfile#L2)):*
> ```Dockerfile
> FROM airhacks/tomee
> MAINTAINER Adam Bien, adam-bien.com
> ```

does this refer to the maintainer of _this_ docker file?

---

*[integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java, line 21 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV-0J1Fq7ajxxci3eK9:-KV-0J1GPssm9K-w-i_Q:b-z50igj) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java#L21)):*
> ```Java
>             ClientConfiguration configuration = null;
> 
>             configuration = new ClientConfiguration(new URL("http://localhost:8080/todo-app/dolphin"), new UiThreadHandler() {
> ```

could use method reference as project has target = 1.8

---

*[integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java, line 33 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV-0Vp2TcLwdERmN_9t:-KV-0Vp2TcLwdERmN_9u:bqvspy5) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java#L33)):*
> ```Java
>                 ClientContext context = ClientContextFactory.connect(configuration).get();
>             } catch (Exception e) {
>                 Assert.fail("Can not create connection", e);
> ```

does this test wait for the timeout to expire?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KV0eWj7C2uYaxokEyWR:bv7f5h) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> this applies the `groovy` plugin to all projects. Do you really need to do this?
</details>
I have no idea how to solve this. Can you change it?

---

*[buildSrc/src/main/groovy/ExecWait.groovy, line 1 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzvOnbs5G16QYxiMn:-KV0cBXyqVsfuMC_uqgz:b-126e3a) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/buildSrc/src/main/groovy/ExecWait.groovy#L1)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> missing license header. All source code must have a license header.
</details>
mmh, that is a good point. I have this snippet from Markus. I will ask him if this class needs a custom header or if we can simply add our header to the class.

---

*[integration-tests/integration-tests.gradle, line 14 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--eKFxmrNqiWIZDTT:-KV0dR_2eZNVMmO-dWZO:b-n829j4) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/integration-tests.gradle#L14)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> have a look at `https://github.com/avast/docker-compose-gradle-plugin`
</details>
I don't know if Docker Compose is running on Travis. If it's working this will be a much better approach. THX for the hint.

---

*[integration-tests/docker-base/payara-integration/todo-app.war, line  at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--6vw9ZqEPPq8maZd:-KV0e3f0IXdvyOTcJnTU:b-gomfct) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/docker-base/payara-integration/todo-app.war#L)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> should this binary be checked in or should it be grabbed from a previous build step?
</details>
Later it should depend on a previous build step. As I said this PR is not finished ;)

---

*[integration-tests/docker-base/tomee-integration/Dockerfile, line 2 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV--wCbC0oP-Qzs8JoI:-KV0eB5I2hQoaoHHEJFv:b2tgwwk) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/integration-tests/docker-base/tomee-integration/Dockerfile#L2)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> does this refer to the maintainer of _this_ docker file?
</details>
Yes, copied it from Adam and missed to remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by aalmiray** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KV0f2QkdsrT3WQrf1Wy:byr85vh) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> I have no idea how to solve this. Can you change it?
</details>
I could change it if I knew what you want to accomplish with this setup. As far as I can tell this PR does not include new Groovy sources in the project.s There's however a new Groovy source found in `buildSrc`. This project is not dependent of the root project's configuration, rather it's the other way round. This means you can apply the groovy plugin in `buildSrc/build.gradle` and remote it form the root build file.

---

*[integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java, line 36 at r3](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KV0gJ_TSSh0mJktECTH:-KV0gJ_UwCVDgmeH2Tqq:b-y9angp) ([raw file](https://github.com/canoo/dolphin-platform/blob/1f14c42fcd4e93ff895cdc0e186043b457efae48/integration-tests/src/test/java/com/canoo/dolphin/integration/ConnectionTest.java#L36)):*
> ```Java
>             ClientConfiguration configuration = null;
> 
>             configuration = new ClientConfiguration(new URL("http://localhost:8080/todo-app/dolphin"), r -> r.run());
> ```

`Runnable::run` not an option? AFAIK IntelliJ should have suggested to use a method reference if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KV0gdYCw4bghbZfUPNz:bbe584x) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> I could change it if I knew what you want to accomplish with this setup. As far as I can tell this PR does not include new Groovy sources in the project.s There's however a new Groovy source found in `buildSrc`. This project is not dependent of the root project's configuration, rather it's the other way round. This means you can apply the groovy plugin in `buildSrc/build.gradle` and remote it form the root build file.
</details>
I thinks that the point. Will try it. THX

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KV0hGudHe8iRzJ5wqeH:b-fnt7su) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> I thinks that the point. Will try it. THX
</details>
No build.gradle in that folder. I thought this is a special directory for Gradle to add plugins, custom task since it's not mentioned in any gradle file. Mhhh, no idea what to do now...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by aalmiray** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[build.gradle, line 48 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/235#-KUzzQu-IdqQZxihjqoh:-KV1HxB-BIX7sL-8XLKm:b3qpttu) ([raw file](https://github.com/canoo/dolphin-platform/blob/25645a59d507b16920bf85478424cc7d16a2afdd/build.gradle#L48)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> No build.gradle in that folder. I thought this is a special directory for Gradle to add plugins, custom task since it's not mentioned in any gradle file. Mhhh, no idea what to do now...
</details>
if there's no `build.gradle` file found under `buildSrc` that means the project is already configured by Gradle using the default conventions; there's nothing to be added ;-) Thus you can safely remove the `apply plugin: 'groovy'` line from the root build file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/235)*

**Comment by hendrikebbers** [comment]
see #248

**Pull request closed without merging**
