### PR TITLE
Custom converter API and optional module with Java 8 Date&time converters

### PR DESCRIPTION
**Pull request by hendrikebbers**
With this PR developers can provide custom converters for DP to provide more data types in the model.

---

This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/263)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/DurationConverterFactory.java, line 28 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4ut3fyA24NShQ-4aC:-KV4ut3gVcrjb0Wpw-QH:b-kzi9jv) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/DurationConverterFactory.java#L28)):*
> ```Java
>     private final static Converter CONVERTER = new DurationConverter();
> 
>     public final static int FIELD_TYPE = 51;
> ```

should this constant be placed at a common place with other constants of the same nature?

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, line 49 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4v7P7vQB0BmWpv1UI:-KV4v7P7vQB0BmWpv1UJ:b-qbz13y) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java#L49)):*
> ```Java
> 
>         @Override
>         public LocalDateTime convertFromDolphin(String value) {
> ```

I'd rather have the method be named `convertFromLiteral` or `convertFromString`.

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, line 57 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4vFqu2vgSH3N0rex8:-KV4vFqxv6NvEbCveBjB:bgb17o6) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java#L57)):*
> ```Java
> 
>         @Override
>         public String convertToDolphin(LocalDateTime value) {
> ```

perhaps rename to `convertToLiteral` or `convertToString`

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/PeriodConverterFactory.java, line 55 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4vi_j_RIAHWOKla9J:-KV4vi_knrMX1GP_r1rm:b6xkrhc) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/PeriodConverterFactory.java#L55)):*
> ```Java
>                 return null;
>             }
>             return Period.parse(value);
> ```

what happens if `parse()` throws `DateTimeParseException` because of an invalid value? Same thing with the other parsing converters

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanUtils.java, line 22 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4wwy4idVEWmRu83t9:-KV4wwy5-SZlkovGmNdr:bbg3uba) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanUtils.java#L22)):*
> ```Java
>  */
> public class BeanUtils {
> ```

if this class is still available then mark it as deprecated and route all of its methods to the corresponding `DolphinUtils` method.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 51 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xPYF2559thaktEyb:-KV4xPYGBT_Auk4XDOU5:b-rztbjq) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L51)):*
> ```Java
> 
>     public int getFieldType(Class<?> clazz) {
>         return getFactory(clazz).getTypeIdentifier();
> ```

what if there's no match for `clazz`?  There may be an NPE

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 55 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xVIQ92dJ6CS_MjE9:-KV4xVIRzGcT6yIqAZbL:b-cn6hsr) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L55)):*
> ```Java
> 
>     public Converter getConverter(Class<?> clazz) {
>         return getFactory(clazz).getConverterForType(clazz);
> ```

possible NPE. see above

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 67 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xbAKQSsbtSeiqIIC:-KV4xbAKQSsbtSeiqIID:b32q4di) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L67)):*
> ```Java
>         }
>         if (foundConverters.size() > 1) {
>             throw new RuntimeException("More than 1 converter instance found to convert " + clazz);
> ```

use another exception type

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 70 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xeJcnbeOzqwojPK2:-KV4xeJcnbeOzqwojPK3:b32q4di) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L70)):*
> ```Java
>         }
>         if (foundConverters.isEmpty()) {
>             throw new RuntimeException("No converter instance found to convert " + clazz);
> ```

use another exception type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/263)*

**Comment by hendrikebbers** [comment]
Review status: 14 of 55 files reviewed at latest revision, 9 unresolved discussions.

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/DurationConverterFactory.java, line 28 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4ut3fyA24NShQ-4aC:-KVUBwhUIQAsUMNM2iNa:bb6un1j) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/DurationConverterFactory.java#L28)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> should this constant be placed at a common place with other constants of the same nature?
</details>
Done

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, line 49 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4v7P7vQB0BmWpv1UI:-KVUCCC-aQDfm5wYxOWZ:b56j9x9) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java#L49)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> I'd rather have the method be named `convertFromLiteral` or `convertFromString`.
</details>
mmh, is "literal" right? Because it will cover String, boolean & number. German translation in dictionary looks like it's only for strings. If you think it's right we can use it. Maybe "convertFromRaw" ?

---

*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/PeriodConverterFactory.java, line 55 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4vi_j_RIAHWOKla9J:-KVUITXau3rWHsUIDupS:b-2kik46) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/PeriodConverterFactory.java#L55)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> what happens if `parse()` throws `DateTimeParseException` because of an invalid value? Same thing with the other parsing converters
</details>
Introduced ValueConverterException

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanUtils.java, line 22 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4wwy4idVEWmRu83t9:-KVUI_txH7IhzLGmcygM:b-hfpv0l) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/BeanUtils.java#L22)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> if this class is still available then mark it as deprecated and route all of its methods to the corresponding `DolphinUtils` method.
</details>
removed

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 51 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xPYF2559thaktEyb:-KVUIhN5flfmDvBJ3peL:bs71he6) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L51)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> what if there's no match for `clazz`?  There may be an NPE
</details>
no, check is in getFactory(Class)

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 55 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xVIQ92dJ6CS_MjE9:-KVUIl_p_d55QnqD94Ee:bs71he6) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L55)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> possible NPE. see above
</details>
no, check is in getFactory(Class)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/263)*

**Comment by hendrikebbers** [comment]
Review status: 14 of 55 files reviewed at latest revision, 9 unresolved discussions.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 67 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xbAKQSsbtSeiqIIC:-KVUO5TEjZldugVnB2WI:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L67)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> use another exception type
</details>
done

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 70 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4xeJcnbeOzqwojPK2:-KVUO77fDCejiYFdPlme:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L70)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> use another exception type
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/263)*

**Comment by netopyr** [comment]
*[platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java, line 49 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/263#-KV4v7P7vQB0BmWpv1UI:-KVURlYGHnV-XpKCv9AZ:b-g8ozyn) ([raw file](https://github.com/canoo/dolphin-platform/blob/d2ffed331bc80523d6592c17d23914dadf5cc896/platform-extras/dolphin-platform-date-time-converter/src/main/java/com/canoo/dolphin/converters/LocalDateTimeConverterFactory.java#L49)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> mmh, is "literal" right? Because it will cover String, boolean & number. German translation in dictionary looks like it's only for strings. If you think it's right we can use it. Maybe "convertFromRaw" ?
</details>
I'd say literal has a different meaning. String is not sufficient. Not sure if raw is really better. The point here is, that a converter converts values from the application domain to something that OpenDolphin can handle and back. Currently this is defined by the capabilities of JSON, therefore my first attempt was convertFromJSON and convertToJSON. But we do not necessarily keep JSON, and these names are inappropriate, too.

I think whatever name you choose, it should not be bound to the current implementation, but should also make sense with other remoting components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/263)*

**Pull request merged**
