### PR TITLE
Some additional methods for the FXWrapper

### PR DESCRIPTION
**Pull request by hendrikebbers**
The methods are needed in a customer project.

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/110)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@netopyr I think that can be reviewed in a short time :)

**Comment by netopyr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 130 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnmrmd6CcHS8txM8pK:-KBnmrmd6CcHS8txM8pL:1984298176) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L130)):*
I would prefer two Functions instead, because you can use method references / lambdas with that. At least we should have a method with two Functions in addition.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 141 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnnYiZg4OIe7HR6wlr:-KBnnYiZg4OIe7HR6wls:396742872) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L141)):*
Are the methods generating a Property<Number> really needed? Wouldn't you use the method wrapDoubleProperty() instead?

---

*[java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXWrapperTest.java, line 23 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBno-26IbZDQzw-IbVr:-KBno-27BSRB0mkjwdAF:195927403) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXWrapperTest.java#L23)):*
Never check for equals when dealing with floating point numbers.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/110)*

**Comment by hendrikebbers** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 130 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnmrmd6CcHS8txM8pK:-KBnqn2uF85Xpd5Lcs3i:477407104) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L130)):*
I'm with you. But this will be a bigger change (since we need to go down to all the binding interfaces). Therefore I created an issue: https://github.com/canoo/dolphin-platform/issues/116

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 141 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnnYiZg4OIe7HR6wlr:-KBnpkWuNpnMnIqIq53_:1256424003) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L141)):*
Yes, we need this method since all the JavaFX Properties that holds numbers (DoubleProperty, etc.) are based on Property<Number> instead of Property<Double>. If you want to define a table column cell value factory this method is very helpful, for example.

---

*[java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXWrapperTest.java, line 23 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBno-26IbZDQzw-IbVr:-KBntcRaf6Tl6Hkh64KZ:677588487) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/test/java/com/canoo/dolphin/client/javafx/FXWrapperTest.java#L23)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/110)*

**Comment by netopyr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 141 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnnYiZg4OIe7HR6wlr:-KBqLv0LT8q4mUQ6xour:-1937804739) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L141)):*
"are based on Property instead of Property"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/110)*

**Comment by hendrikebbers** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 141 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnnYiZg4OIe7HR6wlr:-KBsS3J8Ui1MPBoGdKd_:-1645920343) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L141)):*
Lol, somehow the generic information was removed i my comment :D In JavaFX you have DoubleProperty extends Property < Number > And by doing so you can't bind a Dolphin Platform Property < Double > to a JavaFX DoubleProperty without using a converter or this new method.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/110)*

**Comment by netopyr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java, line 141 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/110#-KBnnYiZg4OIe7HR6wlr:-KBwZY4Qr4E_C7SKwNke:-1546322902) ([raw file](https://github.com/canoo/dolphin-platform/blob/391cf9d62862c67a704eafefee9aadce0490b4b2/java-client-javafx/src/main/java/com/canoo/dolphin/client/javafx/FXWrapper.java#L141)):*
Hmmm, I must be missing something essential here. My main question is: why do we need wrapDoubleInNumberProperty(), when we already have wrapDoubleProperty()?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/110)*

**Comment by hendrikebbers** [comment]
I think we need to discuss if we can solve this in a better way. Therefore I moved the Pull Request to version 0.9

**Pull request closed without merging**
