### PR TITLE
Move some Groovy classes to Java.

### PR DESCRIPTION
**Pull request by aalmiray**
This commit is intended as the beginning of a discussion on how we can
successfully migrate Groovy code to Java. Leveraging Lombok to generate
bytecode similar to the bytecode generated by the Groovy compiler for
example.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/171)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy, line 26 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-KISlbo-WTI0lrQYyHWo:-KISlbo-WTI0lrQYyHWp:1416831635) ([raw file](https://github.com/canoo/dolphin-platform/blob/88e23e2384c0242b225a0d22153a2ed6904af9df/remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy#L26)):*
> ```Groovy
> import java.beans.PropertyChangeEvent
> import java.beans.PropertyChangeListener
> import java.util.function.Function
> ```

We can't use Function here since shared is used in client & server. The server is still based on Java 7

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171)*

**Comment by aalmiray** [comment]
Reviewed 1 of 20 files at r1.
Review status: 1 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy, line 26 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-KISlbo-WTI0lrQYyHWo:-KISnLpkgY4dflcLnwDg:-999280240) ([raw file](https://github.com/canoo/dolphin-platform/blob/88e23e2384c0242b225a0d22153a2ed6904af9df/remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy#L26)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> We can't use Function here since shared is used in client & server. The server is still based on Java 7
</details>
Indeed. A better fix would be to remove the usage of  the `Closure` completely, with an appropriate functional interface equivalent that's specific to the remoting layer, thus no dependencies to Java8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171)*

**Comment by hendrikebbers** [comment]
Review status: 1 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy, line 26 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-KISlbo-WTI0lrQYyHWo:-KISpf-bB-ujOYUCeaU2:1157380063) ([raw file](https://github.com/canoo/dolphin-platform/blob/88e23e2384c0242b225a0d22153a2ed6904af9df/remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy#L26)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> Indeed. A better fix would be to remove the usage of  the `Closure` completely, with an appropriate functional interface equivalent that's specific to the remoting layer, thus no dependencies to Java8
</details>
Yes, I did the same for DP: 
https://github.com/canoo/dolphin-platform/blob/d2503bdf5932ed5153674384e371e0099700dd92/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/util/Callback.java

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171)*

**Comment by blackdrag** [comment]
Reviewed 19 of 20 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy, line 26 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-KISlbo-WTI0lrQYyHWo:-KPT3F5TsbvRDbAagVjV:b-vsmr4e) ([raw file](https://github.com/canoo/dolphin-platform/blob/88e23e2384c0242b225a0d22153a2ed6904af9df/remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy#L26)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> Yes, I did the same for DP: 
> https://github.com/canoo/dolphin-platform/blob/d2503bdf5932ed5153674384e371e0099700dd92/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/util/Callback.java
> 
> 
</details>
which means this PR cannot be approved before this is changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171)*

**Comment by blackdrag** [comment]
This commit does not work on Java7

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-:-KPT4bpqThrQGTI7TQr9:bz1die3)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy, line 26 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/171#-KISlbo-WTI0lrQYyHWo:-KPT7Z85WdhCs9H41W5o:b27zcks) ([raw file](https://github.com/canoo/dolphin-platform/blob/88e23e2384c0242b225a0d22153a2ed6904af9df/remoting/dolphin-remoting-shared/src/main/groovy/org/opendolphin/binding/Binder.groovy#L26)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> which means this PR cannot be approved before this is changed
</details>
yes. This PR should not be part of the next release. I think the best will be a Callback interface in one of our core modules that simply can be used by all other modules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/171)*

**Comment by hendrikebbers** [comment]
I think we can close this since it will not be merged

**Pull request closed without merging**
