### PR TITLE
Qualifier Support for DP

### PR DESCRIPTION
**Pull request by hendrikebbers**
This PR add qualifier support for the Dolphin Platform.

To use qualifiers a QualifierBinder can be injected (see Test example).
The qualifiers of the DP are using generics for a better type safety.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/205)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
I ask myself if we should rename QualifierBinder to PropertyBinder ;)

**Comment by hendrikebbers** [comment]
BindingException is too plain. it could be richer by receiving the property name, identifier and other arguments; crafting the message internally and providing access to some of its args if saved on final fields. IOW BindingException is too close to plain RuntimeException.

**Comment by aalmiray** [comment]
Reviewed 23 of 32 files at r1, 6 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java, line 97 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNC9cS8q4tgiFdwJj3N:-KNC9cS8q4tgiFdwJj3O:1303465178) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java#L97)):*
> ```Java
>         Assert.requireNonNull(type, "type");
>         Assert.requireNonNull(name, "name");
>         for(Field field : getInheritedDeclaredFields(type)) {
> ```

the side effect of this call is to compute the full list of fields and then filter it. Given that we need to find a single one I'd say the behavior of `getInheritedDeclaredFields(type)` should be inlined here, that is, search and filter as you go.

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java, line 13 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNCA4msZLgAPA9SZ0zA:-KNCA4msZLgAPA9SZ0zB:-1475406482) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java#L13)):*
> ```Java
>  * @see PropertyBinder
>  */
> public class Qualifier<T> {
> ```

should this type be subclassed? if not make it `final`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/205)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java, line 97 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNC9cS8q4tgiFdwJj3N:-KNCo2NRwZ3ROhmfLR9I:1956554807) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java#L97)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> the side effect of this call is to compute the full list of fields and then filter it. Given that we need to find a single one I'd say the behavior of `getInheritedDeclaredFields(type)` should be inlined here, that is, search and filter as you go.
</details>
Make sense. Can you fix it? By doing so you can merge the PR.

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java, line 13 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNCA4msZLgAPA9SZ0zA:-KNCo6VRRxPqfHoxTf7X:1956554807) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java#L13)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary>
> should this type be subclassed? if not make it `final`.
</details>
Make sense. Can you fix it? By doing so you can merge the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/205)*

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java, line 97 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNC9cS8q4tgiFdwJj3N:-KPD6BY3dCWK0GoiyMr9:b-7rl0kd) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-core/src/main/java/com/canoo/dolphin/impl/ReflectionHelper.java#L97)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> Make sense. Can you fix it? By doing so you can merge the PR.
</details>
done

---

*[platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java, line 13 \[r3\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/205#-KNCA4msZLgAPA9SZ0zA:-KPD7-Vz_F2DlbihF2ht:b-7rl0kd) ([raw file](https://github.com/canoo/dolphin-platform/blob/b8fe2b4b85595e38ae61fdb963bbd416e12a0ba8/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/binding/Qualifier.java#L13)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> Make sense. Can you fix it? By doing so you can merge the PR.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/205)*

**Pull request merged**
