### PR TITLE
Client connector migrated to java

### PR DESCRIPTION
**Pull request by hendrikebbers**
For several issues we need to refactor the client connector. This PR migrates it to Java for a better refactoring.

---

This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/264)

### CODE REVIEW

**Comment by blackdrag** [comment]
Reviewed 12 of 14 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.java, line 80 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxwfrAwxVajVuCmNLe:-KVxwfrAwxVajVuCmNLf:b-u2hwyb) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.java#L80)):*
> ```Java
>     public AbstractClientConnector(ClientDolphin clientDolphin, ICommandBatcher commandBatcher) {
>         this.clientDolphin = clientDolphin;
>         this.commandBatcher = DefaultGroovyMethods.asBoolean(commandBatcher) ? commandBatcher : new CommandBatcher();
> ```

I think you can replace this with a null check

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/CommandAndHandler.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxx8F__l04PAZBGkan:-KVxx8F__l04PAZBGkao:bo1gf37) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/CommandAndHandler.java#L41)):*
> ```Java
>      */
>     public boolean isBatchable() {
>         if (DefaultGroovyMethods.asBoolean(handler)) return false;
> ```

I think this can be a null check

---

*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 113 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxyrz7zVU52gfDlbR3:-KVxyrz7zVU52gfDlbR4:b-f93y5k) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L113)):*
> ```Groovy
> 	//	}
> 	//	assert msg == exceptionMessage
> 	//}
> ```

why is this test commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/264)*

**Comment by blackdrag** [comment]
Reviewed 1 of 14 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/264)*

**Comment by hendrikebbers** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.java, line 80 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxwfrAwxVajVuCmNLe:-KWX8wNkoAVZDOH0gWDy:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/AbstractClientConnector.java#L80)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> I think you can replace this with a null check
</details>
done

---

*[remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/CommandAndHandler.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxx8F__l04PAZBGkan:-KWX98ImXXRgs3gWj5o1:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/main/groovy/org/opendolphin/core/client/comm/CommandAndHandler.java#L41)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> I think this can be a null check
</details>
done

---

*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 113 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxyrz7zVU52gfDlbR3:-KWX9Wx8dGY2ee44QuHe:b-ya3wbn) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L113)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> why is this test commented out?
</details>
Because the exception handler has now String return value anymore. This was only used in this test. Everything else do not handle a result. Based on this the method is void now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/264)*

**Comment by blackdrag** [comment]
*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 113 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxyrz7zVU52gfDlbR3:-KWXjd5wd6XSL2WDXib1:b-j9lzx4) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L113)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary>
> Because the exception handler has now String return value anymore. This was only used in this test. Everything else do not handle a result. Based on this the method is void now.
</details>
one of use is misunderstanding this test. onException is supposed to be called with an exception to then throw it in the appropriate context or to throw it. In this test the exception is thrown and catched by the shouldFail-method (part of GroovyTestCase, not dolphin) and then return the exception message. If the exception does not appear, you changed the threads this test runs in and what the UI thread is, or you now catch the exception at another place and you have to think about that is really intended. Since you set the ui thread handler here, I cannot imagine it is related to threading. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/264)*

**Comment by hendrikebbers** [comment]
*[remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy, line 113 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/264#-KVxyrz7zVU52gfDlbR3:-KWXlzTMd43aen7M5s_t:b-epvltg) ([raw file](https://github.com/canoo/dolphin-platform/blob/d31b54c83c84613afa059d5fac887c426eb64198/remoting/dolphin-remoting-client/src/test/groovy/org/opendolphin/core/client/comm/ClientConnectorTests.groovy#L113)):*
<details><summary><i>Previously, blackdrag (Jochen Theodorou) wrote…</i></summary>
> one of use is misunderstanding this test. onException is supposed to be called with an exception to then throw it in the appropriate context or to throw it. In this test the exception is thrown and catched by the shouldFail-method (part of GroovyTestCase, not dolphin) and then return the exception message. If the exception does not appear, you changed the threads this test runs in and what the UI thread is, or you now catch the exception at another place and you have to think about that is really intended. Since you set the ui thread handler here, I cannot imagine it is related to threading. 
</details>
ok, since it is already merged I will add an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/264)*

**Pull request merged**
