### PR TITLE
Controller proxy factory

### PR DESCRIPTION
**Pull request by hendrikebbers**
Refactored the creation of the Java client ControllerProxy.

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/106)

### CODE REVIEW

**Comment by aalmiray** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvINs9svqs9TblBfb6:-KAvINs9svqs9TblBfb7:549691691) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java#L44)):*
please explain why this method is deprecated. If there's a replacement then also mention it

---

*[java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJfzRyHwmspbTvyqg:-KAvJfzRyHwmspbTvyqh:-971132718) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java#L1)):*
missing file header

---

*[java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java, line 6 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJSpReAV4RK38sNV7:-KAvJSpReAV4RK38sNV8:151843233) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java#L6)):*
I'd prefer if there was a root `DolphinPlatformException` instead of just using `RuntimeException`.  Also, all exceptions are serializable so please add a `serialVersionUID` field.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanManagerImpl.java, line 24 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJisxzBNwGLO_fFJf:-KAvJisxzBNwGLO_fFJg:-726293857) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanManagerImpl.java#L24)):*
please explain why it's deprecated and if there's an alternative for this class

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, line 74 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvK8ucJAQFoLVTO1Rg:-KAvK8ucJAQFoLVTO1Rh:949078095) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java#L74)):*
hmm this `ControllerProxyFactory` contract is too big. It returns a `CompletableFuture` that wraps a `ControllerProxy`. The previous code required usage of internal DP beans (such as `platformBeanRepository.getInternalAttributesBean()`). I'm afraid this design will force every implementation of the factory to use the bean in one way or another, leading to duplicate code or usage of a base abstract controller factory class.

I envisioned the factory to be a replacement for invoking `new ControllerProxyImpl(...)`. The basic idea of this factory is to decouple `ClientControllerImpl` from `ControllerProxyImpl`.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvL49eF3CS_RLUhJ4i:-KAvL49eF3CS_RLUhJ4j:-284913659) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L1)):*
missing file header. There's bound to be a Maven plugin that takes care of this task (Apache RAT comes to mind). Or switch to Gradle and apply the license plugin ;-)

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvKxPKTC7w3ym80jKS:-KAvKxPKTC7w3ym80jKT:-1139489552) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L12)):*
see comment on `ClientContextImpl`.. This method should return `ControllerProxy<T>`.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLGy5z12IcRulhJ1-:-KAvLGy8rY-Fg1rcFq-C:-1655819099) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java#L19)):*
please validate inputs. check file header

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java, line 11 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLTq2lShIyToRnE0Q:-KAvLTq2lShIyToRnE0R:-427837443) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java#L11)):*
please check inputs, file header.
What's the reasoning for creating a top-level class for this code? This used to be hidden inside `ClientContextImpl`. Please follow the same approach of base interface + default class impl if this type may be superclassed by developers for providing tweaks in their app configuration.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLscDbyqHBrYZJvIy:-KAvLscDbyqHBrYZJvIz:-1971470249) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java#L19)):*
why is this method synchronized? the only state hold by this class is the `clientDolphin` field. It makes no sense to synchronize here.

---

*[java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvMAVDAJxueAxNW1XQ:-KAvMAVDAJxueAxNW1XR:-1508200344) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java#L22)):*
please follow naming conventions and attach `Test`or `Tests` as a suffix

---

*[java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java, line 47 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvMMjqZnwA1RW8d4jY:-KAvMMjqZnwA1RW8d4jZ:993537529) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java#L47)):*
I'd declare the method to throw `Exception` avoiding the `try`/`catch` block

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/106)*

**Comment by hendrikebbers** [comment]
Review status: 7 of 15 files reviewed at latest revision, 12 unresolved discussions.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvINs9svqs9TblBfb6:-KAyHu4jRLsLV_zZcQef:1581643675) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java#L44)):*
The ClientBeanManager extends the BeanManager and therefore provides methods like create() and remove(). Currently Michael and I think that we don't need this methods on the client. The ClientBeanManager class is deprecated since some time. I know that you are currently using methods and that's the point why we don't remove it. But maybe we find a better way to handle the needs on the client. Therefore the API of ClientBeanManager can change completely in a future version.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJfzRyHwmspbTvyqg:-KAyIUWzLfn1ju8SHLo4:676635175) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java#L1)):*
Done

---

*[java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java, line 6 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJSpReAV4RK38sNV7:-KAyK_sQ2JJYdbjL_Q-t:-801768585) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ControllerInitalizationException.java#L6)):*
added UID to all exceptions. Let's think about a general exception hierarchy in an additional issue: https://github.com/canoo/dolphin-platform/issues/107

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanManagerImpl.java, line 24 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvJisxzBNwGLO_fFJf:-KAyL-CsCkCTwf9CxWwW:828723073) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientBeanManagerImpl.java#L24)):*
See my first comment.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, line 74 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvK8ucJAQFoLVTO1Rg:-KAyOhhrX18BmHXvJgT7:-323685689) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java#L74)):*
I avoided this in the first try because this will end in the usage of an additional Executor. I commit a refactoring now that uses a factory that directly returns a ControllerProxy. By doing so the ClientContextImpl will use an Executor internally.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 1 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvL49eF3CS_RLUhJ4i:-KAyLHfwn7x9L73MKB6a:1088875624) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L1)):*
Header added. i create an issue to find a Maven Plugin: https://github.com/canoo/dolphin-platform/issues/108

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLGy5z12IcRulhJ1-:-KAyLdvrKd2ykdQFDslF:676635175) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java#L19)):*
Done

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java, line 11 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLTq2lShIyToRnE0Q:-KAyLjbjL0v0aV9vlX8K:-2071823084) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java#L11)):*
Based on the factory calling a Dolphin command was needed in serval points. That's why I externalized the functionality in a separate class. Since all classes that use the functionality are private classes (all *Impl) I don't think that we need an interface here.
Added Header & NullChecks

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java, line 19 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvLscDbyqHBrYZJvIy:-KAyMLP41YSrz-o85IPi:1669732100) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/DolphinCommandHandler.java#L19)):*
I think I just copied it from the ClientContext. You are right. 

---

*[java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java, line 22 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvMAVDAJxueAxNW1XQ:-KAyMcpVngehFGZfiyx9:511952985) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java#L22)):*
I think we should discuss this. Michael used Test as a prefix in all classes in the client. That's why I did it this way. I'm fine with any naming convention. For now I won't change it but we should define a naming convention and then refactor all tests.

---

*[java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java, line 47 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvMMjqZnwA1RW8d4jY:-KAyNGLiDsGuJqrBnl9t:676635175) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/test/java/com/canoo/dolphin/client/impl/TestDolphinCommandHandler.java#L47)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/106)*

**Comment by hendrikebbers** [comment]
@aalmiray does the last version fit to your needs?

**Comment by aalmiray** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java, line 44 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvINs9svqs9TblBfb6:-KBnzXEpCTeoFfMXgXFu:22559260) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/ClientContext.java#L44)):*
thanks for the explanation :-) it should be in the javadoc too

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/106)*

**Comment by hendrikebbers** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/106#-KAvKxPKTC7w3ym80jKS:-KBsaGCw1aiTa8WtMtBD:-499146009) ([raw file](https://github.com/canoo/dolphin-platform/blob/03efe70acfd0f0aab75e4765c6534c48639771b7/java-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L12)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/106)*

**Pull request merged**
