### PR TITLE
WIP: OldValue of ValueChangedCommand removed

### PR DESCRIPTION
**Pull request by hendrikebbers**
This can not be merged before JS part is ready!
Fix for https://github.com/canoo/dolphin-platform/issues/529

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/537)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
JS part: https://github.com/canoo/dolphin-platform-js/pull/28

**Comment by blackdrag** [comment]
since you removed testStateConflictBetweenClientAndServer, what will now happen in the case described in this test? What happens if two clients update a value before each got the new value?

**Comment by hendrikebbers** [comment]
2 clients never share the same model. What can happen:
The event bus can update a value. But since the event bus is always handled after the client changes this will not end in a conflict. A conflict can only happen if you change the model on the server on a background thread. And this is forbidden. So since the model is always changed on one thread it can not end in a conflict.

**Comment by hendrikebbers** [comment]
By holding the old value you send the content of a value with each change 2 times (old & new value). This is not that hard for an number etc. But a user found out that this has a big impact on the communication speed if you handle big strings. Think about a text with 20.000 chars or so. When you change only 1 char the 20.000 chars will be send 2 times with any change. For the user it get's spooky when he removes the content of the text (like select all and delete). Normally you would think that this will be very fast but since the change command contains the old value it will take some time <- That's how the user found the problem

**Comment by blackdrag** [comment]
so if I change in Session A a specific integer foo from 2->3 and in Session B the equivalent integer from 2->4 and if I then use the event bus to synchronize Session A and Session B and both changes happen roughly at the same time... then what will the value of that integer be in the end? B will change from 2->4 and then the eventbus will cause a value change to 3, right?

**Pull request merged**
