### PR TITLE
WIP: Smaller commands

### PR DESCRIPTION
**Pull request by hendrikebbers**
Refactored all commands on Java side. This PR can not be merged before JS implementation has been refactored

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/548)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
https://github.com/canoo/dolphin-platform-js/pull/30

**Comment by hendrikebbers** [comment]
fix for https://github.com/canoo/dolphin-platform/issues/513

**Comment by hendrikebbers** [comment]
fix for https://github.com/canoo/dolphin-platform/issues/228

**Comment by hendrikebbers** [comment]
Will fix https://github.com/canoo/dolphin-platform/issues/513 and https://github.com/canoo/dolphin-platform/issues/228

**Comment by hendrikebbers** [comment]
@blackdrag @timo0 can someone do a review. This is done. Still WIP because of missing JS

**Comment by blackdrag** [comment]
Reviewed 38 of 64 files at r1, 21 of 22 files at r2.
Review status: 54 of 63 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[platform/dolphin-platform-rpm-client/src/test/java/com/canoo/dolphin/client/util/AbstractTestCommand.java, line 9 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KpM-7rqJr6_xyz9y05O:-KpM-7rqJr6_xyz9y05P:b-eyfig8) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-client/src/test/java/com/canoo/dolphin/client/util/AbstractTestCommand.java#L9)):*
> ```Java
>  */
> public abstract class AbstractTestCommand extends Command{
>     public AbstractTestCommand(String id) {
> ```

why do you need this class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/548)*

**Comment by aalmiray** [comment]
Reviewed 9 of 64 files at r1, 1 of 22 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/platform/client/ClientContextFactory.java, line 54 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYVIM0WpQhTUY2ssL2:-KqYVIM0WpQhTUY2ssL3:bv36m1o) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/platform/client/ClientContextFactory.java#L54)):*
> ```Java
>             @Override
>             public AbstractClientConnector call(final ClientModelStore clientModelStore) {
>                 return new DolphinPlatformHttpClientConnector(clientConfiguration, clientModelStore, OptimizedJsonCodec.getInstance(), new RemotingExceptionHandler() {
> ```

magic singletons are bad design. Also, this implementation assumes two explicit implementations will be used: OptimizedJsoncodec and RemotingExceptionHandler. What if we need different implementations at a later stage?

---

*[platform/dolphin-platform-rpm-client/src/test/java/com/canoo/dolphin/client/util/AbstractTestCommand.java, line 1 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYVlTaBrIygu9xVrqe:-KqYVlTaBrIygu9xVrqf:b8jw4p8) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-client/src/test/java/com/canoo/dolphin/client/util/AbstractTestCommand.java#L1)):*
> ```Java
> package com.canoo.dolphin.client.util;
> ```

missing header

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 55 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWG2L1dyCLtiZ_BZr:-KqYWG2MkvIRJVQaffnR:b-8f8adm) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L55)):*
> ```Java
> import static org.opendolphin.core.comm.CommandConstants.*;
> 
> public class OptimizedJsonCodec implements Codec {
> ```

mark this class as `final`.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 107 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYW37eLH_LBzcf5dJ-:-KqYW37eLH_LBzcf5dJ0:b-q8swon) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L107)):*
> ```Java
>                 final CommandTranscoder encoder = transcoders.get(command.getId());
>                 if (encoder == null) {
>                     throw new RuntimeException("No encoder for command type " + command.getClass() + " found");
> ```

throw a meaningful exception other than `RuntimeException`.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 136 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWAGAdw9bZbNEMjDq:-KqYWAGBTACMtAW18dxB:b-q8swon) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L136)):*
> ```Java
>                 final JsonPrimitive idElement = command.getAsJsonPrimitive("id");
>                 if (idElement == null) {
>                     throw new RuntimeException("Can not encode command without id!");
> ```

throw a meaningful exception other than `RuntimeException`.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 142 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWAvQ6ojUJQzztlOb:-KqYWAvQ6ojUJQzztlOc:b-q8swon) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L142)):*
> ```Java
>                 final CommandTranscoder<?> encoder = transcoders.get(id);
>                 if (encoder == null) {
>                     throw new RuntimeException("Can not encode command of type " + id + ". No matching encoder found!");
> ```

throw a meaningful exception other than `RuntimeException`.

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/FunctionalPresentationModelTests.groovy, line 47 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWQXVtxH3XrslBGa_:-KqYWQXW2AXHSCNVD2Uy:b-l7itg) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/FunctionalPresentationModelTests.groovy#L47)):*
> ```Groovy
> public class FunctionalPresentationModelTests {
> 
>     final private class CreateCommand extends AbstractTestCommand {
> ```

visibility modifier goes first -> `private final`.

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ServerControlledFunctionalTests.java, line 49 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWbFWXrr2Pr2Djvj7:-KqYWbFXoqzEUlbf2zGy:b-dvr2nf) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ServerControlledFunctionalTests.java#L49)):*
> ```Java
>     private ClientDolphin clientDolphin;
> 
>     final private class CreatePmCommand extends AbstractTestCommand {
> ```

visibility modifier comes first -> `private final`.

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ServerControlledFunctionalTests.java, line 50 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYWfY7zVDINfWze-nf:-KqYWfY7zVDINfWze-ng:bwxsj4l) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/comm/ServerControlledFunctionalTests.java#L50)):*
> ```Java
> 
>     final private class CreatePmCommand extends AbstractTestCommand {
>         public CreatePmCommand() {
> ```

all these subclasses can be rewritten as follows

    private abstract class BaseCommand extends AbstractTestCommand {
        private BaseCommand() {
            super(getClass().getSimpleName());
        }
    }

    private final class CreatePmCommand extends BaseCommand {}

---

*[remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/util/AbstractTestCommand.java, line 1 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYX9r0M1-2hmV4UZpz:-KqYX9r0M1-2hmV4UZq-:b8jw4p8) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/remoting/dolphin-remoting-combined/src/test/groovy/org/opendolphin/core/util/AbstractTestCommand.java#L1)):*
> ```Java
> package org.opendolphin.core.util;
> ```

missing header

---

*[remoting/dolphin-remoting-server/src/test/groovy/org/opendolphin/core/server/util/AbstractTestCommand.java, line 1 at r2](https://reviewable.io:443/reviews/canoo/dolphin-platform/548#-KqYXGdXoocU8y75dwnZ:-KqYXGdYz2F8I8jrrEOx:b8jw4p8) ([raw file](https://github.com/canoo/dolphin-platform/blob/181a31eef54cacf49b885118853e98c0c297247b/remoting/dolphin-remoting-server/src/test/groovy/org/opendolphin/core/server/util/AbstractTestCommand.java#L1)):*
> ```Java
> package org.opendolphin.core.server.util;
> ```

missing header

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/548)*

**Comment by hendrikebbers** [comment]
Closed this based on new PR #585

**Pull request closed without merging**
