### PR TITLE
Enable BlindCommandBatcher by default on Java clients

### PR DESCRIPTION
**Pull request by netopyr**
We should always use the BlindCommandBatcher by default when possible.

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/115)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
The code looks absolutely ok :)
To be true I have no idea what the BlindCommandBatcher exactly does and therefore I can't give real feedback. Maybe @netopyr  and @aalmiray can have a short discussion if it will end in any new problems (for example based on command merge)

**Comment by Dierk** [comment]
using the command batcher is absolutely needed. Otherwise, all commands from the client will be sent as single requests to the server. The command batcher puts many commands in one request.
One can additionally use merging for value change commands. This results in two commands
0 -> 1
1 -> 2
to be sent as one single value change 0 -> 2.
This is usually what we want. The exceptions are use cases where on the server side one wants to do something unusual like counting the single value changes.

**Comment by hendrikebbers** [comment]
@Dierk What I still don't know: When will such a merge happen? Only if the second ValueChangeCommands comes directly after the first one? What happens if a custom command is between the 2 VCC?

**Comment by Dierk** [comment]
a possible merge happens when the two applicable value change commands are both in set of sendable "blinds" (commands with no onFinishedHandler attached) in this batch. 
A named command in "sandwich position" would only disable the merging if it is not blind (i.e. when it has an onFinishedHandler).
The mergeValueChanges property is false by default.

**Comment by hendrikebbers** [comment]
This means: By default no ValueChangeCommands will be merged (can be activated in the batcher). Only commands that are between 2 Commands with an OnFinishHandler will be merged since Commands with OnFinishHandler will always trigger a flush / send. Right?

**Comment by hendrikebbers** [comment]
I think we can merge this without any problem if my last statement is valid. In that case the merge isn't activated and we only batch commands in requests. Sounds good :) In this case we can discuss the handling of the merge in a later version.

**Comment by hendrikebbers** [comment]
@netopyr We need a merge here. Will you do this?

**Pull request merged**
