### PR TITLE
Controller test support for Spring

### PR DESCRIPTION
**Pull request by hendrikebbers**
I merged my old test approach in the new structure. With this version all tests are running. There is still an issue with the event bus (Thread.sleep is needed) but this should be refactored when we refactor the event bus.
The new module provides test support for Unit and TestNG. As a next step this can be splitted in 3 Parts: 
- basic test support classes
- JUnit support
- TestNG support

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/178)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Merged Master in Branch

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/ControllerUnderTest.java, line 19 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKdBC9URo-ZEg0-q11:-KJKdBCAFg6bmx4-yDLk:1848811794) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/ControllerUnderTest.java#L19)):*
> ```Java
> 
> import com.canoo.dolphin.client.Param;
> ```

Add javadoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, line 34 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKddL3zwPm20VwxHAR:-KJKddL4r-c5bcgyj26u:1060478047) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java#L34)):*
> ```Java
> @WebAppConfiguration
> @SpringApplicationConfiguration(classes = DolphinPlatformSpringTestBootstrap.class)
> public class SpringJUnitControllerTest extends AbstractJUnit4SpringContextTests implements ControllerTest{
> ```

make this class abstract

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java, line 54 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKduGCC1JiYeb5ih5e:-KJKduGCC1JiYeb5ih5f:1074974365) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringJUnitControllerTest.java#L54)):*
> ```Java
>                         proxy.invoke(actionName, params).get();
>                     } catch (Exception e) {
>                         throw new ControllerTestException("Error in action", e);
> ```

change comment in something like "Error in action invocation"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringTestNGControllerTest.java, line 54 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKeA964BxBmbV--VwG:-KJKeA964BxBmbV--VwH:1074974365) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/SpringTestNGControllerTest.java#L54)):*
> ```Java
>                         proxy.invoke(actionName, params).get();
>                     } catch (Exception e) {
>                         throw new ControllerTestException("Error in action", e);
> ```

change comment in something like "Error in action invocation"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestContext.java, line 32 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKep1meOfCHJtng8yS:-KJKep1meOfCHJtng8yT:-1752123503) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestContext.java#L32)):*
> ```Java
>  * Created by hendrikebbers on 20.05.16.
>  */
> public class DolphinTestContext extends DolphinContext {
> ```

remove created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestContext.java, line 60 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKfCgguv5p771nljMY:-KJKfCghEdjabUWa843p:-1479766914) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/DolphinTestContext.java#L60)):*
> ```Java
>             public DefaultServerDolphin create() {
>                 DefaultServerDolphin defaultServerDolphin =  config.getServerDolphin();
>                 return defaultServerDolphin;
> ```

inline variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestDolphinFactory.java, line 24 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKfJUrkYJB_bOt3SV4:-KJKfJUsprs5bA26eKkO:-1752123503) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/main/java/com/canoo/dolphin/test/impl/TestDolphinFactory.java#L24)):*
> ```Java
> 
> /**
>  * Created by hendrikebbers on 05.02.16.
> ```

remove created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Review status: 0 of 20 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java, line 97 \[r4\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/178#-KJKgl0NzxqKtH7Wn6pu:-KJKgl0NzxqKtH7Wn6pv:1707879089) ([raw file](https://github.com/canoo/dolphin-platform/blob/3f490d6e2c0d93d67d377fc9a61dc0d8d0421ff9/platform-extras/dolphin-platform-spring-controller-tester/src/test/java/com/canoo/dolphin/test/TestNGDemoTest.java#L97)):*
> ```Java
>         controller.invoke("sendEvent");
> 
>         //Still a workaround to wait till next request
> ```

add reference to issue #64 into comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Comment by AndreasEhret** [comment]
Reviewed 13 of 25 files at r1, 5 of 5 files at r2, 1 of 2 files at r3, 1 of 5 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/178)*

**Pull request merged**
