### PR TITLE
Remoting project

### PR DESCRIPTION
**Pull request by aalmiray**
Pulls in a copy of canoo/open-dolphin @ 9ba5c35

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/154)

### CODE REVIEW

**Comment by aalmiray** [comment]
Note that this PR pulls in Java/Groovy projects only. The JS code must be handled in a separate PR. Waiting for @netopyr to suggest the ideal JS module layout.

**Comment by hendrikebbers** [comment]
All JavaFX based tests are failing at travis.

**Comment by hendrikebbers** [comment]
@aalmiray still working on this one or can I test / review it?

**Comment by aalmiray** [comment]
The build is green. You can test it now

**Comment by hendrikebbers** [comment]
I can build everything but when I start the sample I will get an exception:

Server start: ./gradlew :todo-server-spring:run
Client start: ./gradlew :todo-client:run

Exception in the server when clients starts:

java.lang.ClassNotFoundException: com.canoo.dolphin.internal.EventDispatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:102)
	at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)

**Comment by aalmiray** [comment]
Can't reproduce on a clean build using both command line and IDE as launchers. Could it be that your environment has out of date artifacts?

**Comment by hendrikebbers** [comment]
I started with ./gradlew clean

**Comment by hendrikebbers** [comment]
All in command line

**Comment by hendrikebbers** [comment]
I think I need some help here. It's not working for me

**Comment by hendrikebbers** [comment]
Updated Gradle but it's still not working:

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.11.2 x86_64

**Comment by hendrikebbers** [comment]
KumuluzEE example is still not working here but the rest looks good. From my point of view we can merge this. Don't know if you want to change anything.

**Comment by aalmiray** [comment]
OK to merge then

**Comment by hendrikebbers** [comment]
Done

**Pull request merged**
