### PR TITLE
LogConfiguration

### PR DESCRIPTION
**Pull request by hendrikebbers**
Basic configuration for OD logging

[Review on Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/94)

### CODE REVIEW

**Comment by netopyr** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3jBTTFjGcKxFknIUM:-KD3jBTUke2DeZqGno0I:767204659) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L57)):*
I usually prefer to have a verbose level set by default and switch to something like SEVERE explicitly in production.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 80 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3k22SgzqJQE41keF2:-KD3k22SgzqJQE41keF3:-26709174) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L80)):*
Maybe it makes sense to provide a builder for the ClientConfiguration. It is not consistent to set some values via constructor and others via setter.

---

*[java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java, line 46 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3joUTCyy8Nq16--HG:-KD3joUTCyy8Nq16--HH:498305067) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java#L46)):*
How can I configure this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/94)*

**Comment by hendrikebbers** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3jBTTFjGcKxFknIUM:-KD4KLG_EH7pe7-9zcFF:2093455127) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L57)):*
The complete OD communication is logged on INFO. 

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 80 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3k22SgzqJQE41keF2:-KD4L0GY5WFcnJrYkvEB:-1595237786) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L80)):*
I created an issue: https://github.com/canoo/dolphin-platform/issues/128

---

*[java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java, line 46 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3joUTCyy8Nq16--HG:-KD4KTPeGHAj45nVVx89:-2043373763) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-server/src/main/java/com/canoo/dolphin/server/servlet/DolphinPlatformBootstrap.java#L46)):*
Oh, you can't. We have an open issue to provide a configuration for the server: https://github.com/canoo/dolphin-platform/issues/95

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/94)*

**Comment by hendrikebbers** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3jBTTFjGcKxFknIUM:-KD4L3hE25VPxeSNle25:-1484304625) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L57)):*
So if you don't use WARN or SEVERE you can't find anything in the logging since it's full of OD communication logging. Would be ok to switch to WARN for me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/canoo/dolphin-platform/94)*

**Comment by hendrikebbers** [comment]
see #134

**Comment by aalmiray** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java, line 57 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-KD3jBTTFjGcKxFknIUM:-KGXX5E2BVwNAL3h56vL:148445849) ([raw file](https://github.com/canoo/dolphin-platform/blob/1670c3cb7717f0fbe971592ce7677c7ec8ca6ece/java-client/src/main/java/com/canoo/dolphin/client/ClientConfiguration.java#L57)):*
Agreed. OD is too chatty. Better switch this logging level to a higher setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/94)*

**Comment by blackdrag** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/94#-:-KGXbQ3k7xMvoQXSqbBq:1417088721)*

**Pull request merged**
