### PR TITLE
Type fix

### PR DESCRIPTION
**Pull request by netopyr**
This fix corrects the type conversion and adds support for Date, Calendar, and Enums.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/141)

### CODE REVIEW

**Comment by netopyr** [comment]
This is the suggested fix for #97

**Comment by aalmiray** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientControllerActionCallBean.java, line 42 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXUWTFSkUWQDLBDBqJ:-KGXUWTFSkUWQDLBDBqK:2061530785) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientControllerActionCallBean.java#L42)):*
could this value ever be null? if so an NPE will be thrown in the next line

---

*[java-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXVB8hy8vCl7XpzN9u:-KGXVB8hy8vCl7XpzN9v:1716585809) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L32)):*
what happened with the previous javadoc?

---

*[java-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 126 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXVK1nP9UJPgjoBtzm:-KGXVK1nP9UJPgjoBtzn:-686357327) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L126)):*
why doesn't this interface use generic types for input/output values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/141)*

**Comment by blackdrag** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/141)*

**Comment by netopyr** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java-client/src/main/java/com/canoo/dolphin/client/impl/ClientControllerActionCallBean.java, line 42 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXUWTFSkUWQDLBDBqJ:-KGkBTr6JzhJCXQy8g5x:-467915377) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-client/src/main/java/com/canoo/dolphin/client/impl/ClientControllerActionCallBean.java#L42)):*
fixed

---

*[java-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 32 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXVB8hy8vCl7XpzN9u:-KGkByYdRSOhPRtJh0f4:-1579224552) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L32)):*
It is outdated and does not apply anymore.

---

*[java-core/src/main/java/com/canoo/dolphin/impl/Converters.java, line 126 \[r1\]](https://reviewable.io:443/reviews/canoo/dolphin-platform/141#-KGXVK1nP9UJPgjoBtzm:-KGkC4PKQhgJ0RuPmsB7:-1165447404) ([raw file](https://github.com/canoo/dolphin-platform/blob/882040b92ea0a7e81a2d35f3f281387d79916a57/java-core/src/main/java/com/canoo/dolphin/impl/Converters.java#L126)):*
I do not see much value in this as we do not make much use of such information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/141)*

**Comment by hendrikebbers** [comment]
@netopyr Can we merge this request?

**Pull request merged**
