### PR TITLE
parent-child-relation

### PR DESCRIPTION
**Pull request by hendrikebbers**
Added hierarchy support for controllers (Java server & Java client).
This PR should be reviewed but not merged until the JS part is ready

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/514)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
see https://github.com/canoo/dolphin-platform/issues/382

**Comment by aalmiray** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, line 69 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk83EiQ2P0z0cNcYXN:-Kmk83EjqsK2BeBe1dPf:b-4k8sbi) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java#L69)):*
> ```Java
>         }
> 
>         return controllerProxyFactory.<T>create(name, null).handle(new BiFunction<ControllerProxy<T>, Throwable, ControllerProxy<T>>() {
> ```

specifying `null` as an argument is a code smell. Provide a better option such as `create(String)`. 

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 24 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8JieeJCL4xF_NeSa:-Kmk8JieeJCL4xF_NeSb:byr4ffv) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L24)):*
> ```Java
> public interface ControllerProxyFactory {
> 
>     <T> CompletableFuture<ControllerProxy<T>> create(String name, String parentControllerId);
> ```

see above

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java, line 53 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8TuGDeTFXbF7RLYF:-Kmk8TuGDeTFXbF7RLYG:bmrp5jr) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java#L53)):*
> ```Java
>         final CreateControllerCommand createControllerCommand = new CreateControllerCommand();
>         createControllerCommand.setControllerName(name);
>         createControllerCommand.setParentControllerId(parentControllerId);
> ```

handle potential `null` value for `parentControllerId`.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 23 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8jaN5-IAdyFJEZzg:-Kmk8jaOL_tiH9-Lz6OU:b-oe1is4) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L23)):*
> ```Java
> import com.canoo.dolphin.impl.commands.DestroyControllerCommand;
> import com.canoo.impl.platform.core.Assert;
> import com.google.gson.*;
> ```

I thought star imports were frowned upon in this codebase.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 5 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8s1HNL1XdUVfiZsf:-Kmk8s1HNL1XdUVfiZsg:b-jfny9x) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L5)):*
> ```Java
> import com.canoo.dolphin.impl.commands.CallActionCommand;
> import com.canoo.impl.platform.core.Assert;
> import com.google.gson.JsonArray;
> ```

how many JSON libraries does the project have as dependencies at this point?

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-Kmk9Nna_b0hk8g0gom3:b-mwkraz) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
> ```Java
>         try {
>             final CallActionCommand command = new CallActionCommand();
>             command.setControllerId(jsonObject.getAsJsonPrimitive(CONTROLLER_ID).getAsString());
> ```

can be shortened to `jsonObject.getAsString(CONTROLLER_ID)`. Look for other places where usages of the GSON API can be simplified.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 16 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9xrEYzkMnwySg4zY:-Kmk9xrEYzkMnwySg4zZ:bwcojqa) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L16)):*
> ```Java
>     private String actionName;
> 
>     private Map<String, Object> params = new HashMap<>();
> ```

make it `final`

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkA-NWeIrXHD52Yfz1:-KmkA-NWeIrXHD52Yfz2:b-a6ogoi) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L41)):*
> ```Java
> 
>     public Map<String, Object> getParams() {
>         return params;
> ```

return immutable view

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 45 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9qKBPQz7ggPrUW6O:-Kmk9qKBPQz7ggPrUW6P:b-e9juw) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L45)):*
> ```Java
> 
>     public void addParam(final String name, final Object value) {
>         Assert.requireNonBlank(name, "name");
> ```

does it make sense to accept `null` as a value?

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContext.java, line 248 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAGPpbJaiw6_M4Vfq:-KmkAGPq5Q8PGZnGJrfv:bb7phvt) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContext.java#L248)):*
> ```Java
>             throw new IllegalStateException("An action was called before the init-command was sent.");
>         }
>         //TODO: Remove this. Should bve handled by commands.
> ```

typo

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java, line 27 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAP4SHK17J37UA_gZ:-KmkAP4SHK17J37UA_g_:b-ciiyjf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java#L27)):*
> ```Java
> import com.canoo.impl.server.model.ServerBeanBuilder;
> import com.canoo.platform.core.functional.Subscription;
> import com.canoo.platform.server.*;
> ```

star imports again

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/ParentController.java, line 1 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAfEEWOIk0kVbPyRC:-KmkAfEFHuAAxlD8XBYh:be96vd4) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/ParentController.java#L1)):*
> ```Java
> package com.canoo.platform.server;
> ```

missing license headers

---

*[remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/Command.java, line 51 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAj5y7nljbxEB-iPB:-KmkAj5zmOLs1K35pBiK:bsyg942) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/Command.java#L51)):*
> ```Java
>     //TODO: REMOVE THIS!!!!!!!!!!
>     private static String idFor(final Class commandClass) {
>         String id = commandClass.getSimpleName();
> ```

specify why you need to remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by hendrikebbers** [comment]
THX @aalmiray for review :)

**Comment by hendrikebbers** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java, line 69 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk83EiQ2P0z0cNcYXN:-KmkLf3IWWiWMyUqJhgo:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ClientContextImpl.java#L69)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

specifying `null` as an argument is a code smell. Provide a better option such as `create(String)`. 
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java, line 24 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8JieeJCL4xF_NeSa:-KmkLfubDfgPNa6I4kJ7:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactory.java#L24)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

see above
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java, line 53 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8TuGDeTFXbF7RLYF:-KmkLvQ5S_aiLaVEaHL_:b-wcq9r7) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-client/src/main/java/com/canoo/dolphin/client/impl/ControllerProxyFactoryImpl.java#L53)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

handle potential `null` value for `parentControllerId`.
</blockquote></details>

mmh, I think this is not needed since parentControllerId can be null. But I added an if around it. In a later PR I will define all command fields as final so that you can create them only by using the constructor (already done in JS).

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java, line 23 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8jaN5-IAdyFJEZzg:-KmkN-cuqda44XMioszR:b-12t99m) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/OptimizedJsonCodec.java#L23)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

I thought star imports were frowned upon in this codebase.
</blockquote></details>

ARGH, new IntelliJ. Done

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 5 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk8s1HNL1XdUVfiZsf:-KmkN23lAomBxUTiTEZJ:b-kej35j) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L5)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

how many JSON libraries does the project have as dependencies at this point?
</blockquote></details>

Only GSON ;)
Groovy is removed at runtime.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-KmkNGROywX0_7GYinBT:bkfk834) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

can be shortened to `jsonObject.getAsString(CONTROLLER_ID)`. Look for other places where usages of the GSON API can be simplified.
</blockquote></details>

no, we can not do this since this is not part of the JsonObject (in the GSON version we are using). Created issue: https://github.com/canoo/dolphin-platform/issues/515

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 16 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9xrEYzkMnwySg4zY:-KmkNpH029rZPO3og_fN:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L16)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

make it `final`
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkA-NWeIrXHD52Yfz1:-KmkNojvga8V5AZ2Ckpi:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L41)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

return immutable view
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java, line 45 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9qKBPQz7ggPrUW6O:-KmkNrFIuRH3QOQhFPsS:bwyrt4q) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/commands/CallActionCommand.java#L45)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

does it make sense to accept `null` as a value?
</blockquote></details>

yes. Maybe the action method on the server accepts it. I think it would be wrong to not allow a null value for a param in general

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContext.java, line 248 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAGPpbJaiw6_M4Vfq:-KmkO9oea7Xx_Un_WCtV:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/context/DolphinContext.java#L248)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

typo
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java, line 27 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAP4SHK17J37UA_gZ:-KmkO8jdApC8RkaPnUKd:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/impl/server/controller/ControllerHandler.java#L27)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

star imports again
</blockquote></details>

done

---

*[platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/ParentController.java, line 1 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAfEEWOIk0kVbPyRC:-KmkOP_MgQ8hExpdQ5as:bb7f2mf) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-server/src/main/java/com/canoo/platform/server/ParentController.java#L1)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

missing license headers
</blockquote></details>

done

---

*[remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/Command.java, line 51 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-KmkAj5y7nljbxEB-iPB:-KmkLQey-Dk8so4Eyozm:b-g7vc7i) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/remoting/dolphin-remoting-shared/src/main/java/org/opendolphin/core/comm/Command.java#L51)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

specify why you need to remove this
</blockquote></details>

see https://github.com/canoo/dolphin-platform/issues/513 (added this in the comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by aalmiray** [comment]
Reviewed 9 of 136 files at r2.
Review status: 15 of 142 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-KmkRN636R0ELx7Yj7jA:bz2pl5m) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary><blockquote>

no, we can not do this since this is not part of the JsonObject (in the GSON version we are using). Created issue: https://github.com/canoo/dolphin-platform/issues/515
</blockquote></details>

See https://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/JsonObject.html
https://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/JsonElement.html#getAsString--

current GSON version used in the project is 2.7. This method existed in previous versions (2.6.2). Latest version (2.8.1) also has this method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by hendrikebbers** [comment]
*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-KmkT1UIg7EVqaiVK9yq:bun9fur) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

See https://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/JsonObject.html
https://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/JsonElement.html#getAsString--

current GSON version used in the project is 2.7. This method existed in previous versions (2.6.2). Latest version (2.8.1) also has this method.
</blockquote></details>

Wrong method ;) String parameter is missing. The method that you have mentioned is the one that we use. We can create a static helper method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by aalmiray** [comment]
Review status: 14 of 142 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-KmkTjGDNy_wse5TCtNs:b-v2agnc) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary><blockquote>

Wrong method ;) String parameter is missing. The method that you have mentioned is the one that we use. We can create a static helper method.
</blockquote></details>

ah got it. It's good to go as is then :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by hendrikebbers** [comment]
*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-KmkZx-ZyVM39CYLTyLq:b-qat8p2) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, aalmiray (Andres Almiray) wrote…</i></summary><blockquote>

ah got it. It's good to go as is then :)
</blockquote></details>

Defined some helper methods in base class ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by hendrikebbers** [comment]
*[platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java, line 41 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/514#-Kmk9Nna_b0hk8g0gom2:-Kmkn8PZQc99I28zfWBq:b-896fix) ([raw file](https://github.com/canoo/dolphin-platform/blob/7c24addf2372b0d620e346288aff048e4a8b3484/platform/dolphin-platform-rpm-common/src/main/java/com/canoo/dolphin/impl/codec/encoders/CallActionCommandEncoder.java#L41)):*
<details><summary><i>Previously, hendrikebbers (Hendrik Ebbers) wrote…</i></summary><blockquote>

Defined some helper methods in base class ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/514)*

**Comment by timo0** [comment]
LGTM

**Pull request merged**
