### PR TITLE
WIP: Remove EmptyCommand class.

### PR DESCRIPTION
**Pull request by h93xV2**
In response to issue #598. 

I removed the EmptyCommand class and references to it. This included removing the EmptyCommandEncoder class. In the tests for dolphin-platform-remoting-client, I swapped references to EmptyCommand with ChangedValueCommand. As such, it passes all tests using 

`./gradlew :dolphin-platform-remoting-client:test`

without having to change the entire structure of the test files.

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/690)

### CODE REVIEW

**Comment by h93xV2** [comment]
Noticed that some commits were made to the base branch, so I did a rebase.

**Comment by h93xV2** [comment]
Still passes tests executed with

`./gradlew :dolphin-platform-remoting-client:test`

**Comment by hendrikebbers** [comment]
@h93xV2 Dolphin Platform does not only have a java client. We need to check if the ´EmptyCommand´ is not used in JS: https://github.com/canoo/dolphin-platform-js
Will you do it or should I have a look. If ´EmptyCommand´ is not used in JS or a PR remove the usage this PR can be merged :)
Very good work so far!

**Comment by hendrikebbers** [comment]
For the sync() you changed EMptyCommand to ValueChange commend. Here JS and the Java must be checked if it is ok to send an empty ValueChange command. I hope this is ok since I really like this idea :)

**Comment by h93xV2** [comment]
@hendrikebbers I will look into both of those things you mentioned. Thanks for taking a close look at my work so far!

**Comment by h93xV2** [comment]
@hendrikebbers Just finished researching the two topics you brought up. Here's what I found:

1. Dolphin Platform JS (does not have an EmptyCommand)[https://github.com/canoo/dolphin-platform-js/search?utf8=%E2%9C%93&q=EmptyCommand&type=], so that works out. 
2. [ValueChangedCommand has a default, no-args ctor](https://github.com/canoo/dolphin-platform/blob/4f985ca81e1a873bafb89cfc1db9dd8420695f87/platform/dolphin-platform-remoting-common/src/main/java/com/canoo/dp/impl/remoting/legacy/communication/ValueChangedCommand.java), which is why all the tests still run so nicely. In other words, it is okay for Dolphin Platform Java to send an empty ValueChangedCommand.
3. Dolphin Platform JS's ValueChangedCommand [also has a no-args ctor](https://github.com/canoo/dolphin-platform-js/blob/1854867eaab1812a2d0ac6959cf13a41696dd54a/src/commands/impl/valueChangedCommand.js) so it is fine to use an empty one.

I believe that's everything. Did I miss anything?

**Comment by h93xV2** [comment]
Rebased to keep my fork up-to-date with the master repo.

**Comment by hendrikebbers** [comment]
sounds good :) I will have a deeper look at the end of the week to check if anything is missing.

**Comment by h93xV2** [comment]
@hendrikebbers I actually, just now, caught a mistake that I made. I have to update `TestOptimizedJsonCodec.java` before this PR can be merged.

**Comment by hendrikebbers** [comment]
Best is to to 
Gradle clean build 
in the root folder of the project. By doing so all modules will be tested.

**Comment by h93xV2** [comment]
Yes, definitely. I'll stop testing single parts of the project. Looks like this might take a few days to get sorted out on my end.

**Comment by h93xV2** [comment]
@hendrikebbers Got things done sooner than I anticipated. When you get a chance, I think one more review would be helpful.

**Comment by hendrikebbers** [comment]
Will try to do this on friday :)

**Comment by h93xV2** [comment]
@hendrikebbers Today I tried to update my fork and saw that there are conflicts. Git is telling me that I can't rebase due to EmptyCommand being modified in commit `2acd0b61ac36bfc97bc76a41f82909531b30cd8b` even though I looked at that commit and it was not modified there.

Any thoughts on how this can be resolved?

**Comment by h93xV2** [comment]
Disregard my last comment. I did the research on my own and found out where the conflicts were. Conflicts should be solved and this PR should be ready to merge.

**Comment by h93xV2** [comment]
@hendrikebbers Disregard my last comment. I did the research on my own and found out where the conflicts were. Conflicts should be solved and this PR should be ready to merge.

**Pull request closed without merging**
