### PR TITLE
Core module as common base added

### PR DESCRIPTION
**Pull request by hendrikebbers**
Core module that do not contain any rpm code added

---
This change is [Reviewable](https://reviewable.io/reviews/canoo/dolphin-platform/486)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@kunsingh @timo0 maybe anyone can review this? :)

**Comment by timo0** [comment]
Reviewed 197 of 200 files at r1.
Review status: 113 of 116 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[settings.gradle, line 21 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/486#-KkqVzrYmiI_SmLuabRM:-KkqVzrZrT8bfGzyII54:befxo2l) ([raw file](https://github.com/canoo/dolphin-platform/blob/de08d3d3a3683d309cf339ca26476f6ef5993685/settings.gradle#L21)):*
> ```Gradle
> include 'platform-extras/dolphin-platform-distributed-eventbus'
> 
> include 'documentation'
> ```

why you changed the order of this one?

---

*[platform-examples/todo-example/todo-server-spring/src/main/resources/application.properties, line 25 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/486#-KkqVZH9uRx9zNr-2LDl:-KkqVZH9uRx9zNr-2LDm:b-qkxlpe) ([raw file](https://github.com/canoo/dolphin-platform/blob/de08d3d3a3683d309cf339ca26476f6ef5993685/platform-examples/todo-example/todo-server-spring/src/main/resources/application.properties#L25)):*
> ```INI
> 
> 
> logging.level.
> ```

this seams not completed yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/486)*

**Comment by timo0** [comment]
Reviewed 1 of 200 files at r1.
Review status: 114 of 116 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/486)*

**Comment by hendrikebbers** [comment]
*[settings.gradle, line 21 at r1](https://reviewable.io:443/reviews/canoo/dolphin-platform/486#-KkqVzrYmiI_SmLuabRM:-Klw1QwGyLnWvrRrKhXD:b-859ck8) ([raw file](https://github.com/canoo/dolphin-platform/blob/de08d3d3a3683d309cf339ca26476f6ef5993685/settings.gradle#L21)):*
<details><summary><i>Previously, timo0 (Timo Brandstätter) wrote…</i></summary><blockquote>

why you changed the order of this one?
</blockquote></details>

I think it makes more sense:
APIs
Tests
Samples

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/canoo/dolphin-platform/486)*

**Pull request merged**
